let names =
  [
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"alloc","path":[{"data":{"TypeNs":"vec"},"disambiguator":0},{"data":"Impl","disambiguator":0},{"data":{"ValueNs":"new"},"disambiguator":0}],"index":[5,6703]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"alloc","path":[{"data":{"TypeNs":"vec"},"disambiguator":0},{"data":"Impl","disambiguator":1},{"data":{"ValueNs":"push"},"disambiguator":0},{"data":{"LifetimeNs":"'_"},"disambiguator":0}],"index":[5,9335]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"alloc","path":[{"data":{"TypeNs":"vec"},"disambiguator":0},{"data":"Impl","disambiguator":1},{"data":{"ValueNs":"push"},"disambiguator":0}],"index":[5,6777]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"alloc","path":[{"data":{"TypeNs":"vec"},"disambiguator":0},{"data":"Impl","disambiguator":9}],"index":[5,6848]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"alloc","path":[{"data":{"TypeNs":"vec"},"disambiguator":0},{"data":{"TypeNs":"Vec"},"disambiguator":0}],"index":[5,6696]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"alloc","path":[{"data":{"TypeNs":"alloc"},"disambiguator":0},{"data":"Impl","disambiguator":1}],"index":[5,116]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"alloc","path":[{"data":{"TypeNs":"alloc"},"disambiguator":0},{"data":{"TypeNs":"Global"},"disambiguator":0}],"index":[5,7004]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"marker"},"disambiguator":0},{"data":{"TypeNs":"Sized"},"disambiguator":0}],"index":[2,2689]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"ops"},"disambiguator":0},{"data":{"TypeNs":"range"},"disambiguator":0},{"data":{"TypeNs":"Range"},"disambiguator":0},{"data":{"ValueNs":"start"},"disambiguator":0}],"index":[2,39162]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"ops"},"disambiguator":0},{"data":{"TypeNs":"range"},"disambiguator":0},{"data":{"TypeNs":"Range"},"disambiguator":0},{"data":{"ValueNs":"end"},"disambiguator":0}],"index":[2,39163]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"ops"},"disambiguator":0},{"data":{"TypeNs":"range"},"disambiguator":0},{"data":{"TypeNs":"Range"},"disambiguator":0}],"index":[2,39160]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"ops"},"disambiguator":0},{"data":{"TypeNs":"range"},"disambiguator":0}],"index":[2,39160]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"ops"},"disambiguator":0},{"data":{"TypeNs":"arith"},"disambiguator":0},{"data":"Impl","disambiguator":41}],"index":[2,32300]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"ops"},"disambiguator":0},{"data":{"TypeNs":"arith"},"disambiguator":0},{"data":{"TypeNs":"Add"},"disambiguator":0},{"data":{"TypeNs":"Output"},"disambiguator":0}],"index":[2,2752]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"ops"},"disambiguator":0},{"data":{"TypeNs":"arith"},"disambiguator":0},{"data":{"TypeNs":"Add"},"disambiguator":0},{"data":{"ValueNs":"add"},"disambiguator":0}],"index":[2,2753]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"ops"},"disambiguator":0},{"data":{"TypeNs":"arith"},"disambiguator":0},{"data":{"TypeNs":"Add"},"disambiguator":0}],"index":[2,2750]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"ops"},"disambiguator":0},{"data":{"TypeNs":"deref"},"disambiguator":0},{"data":{"TypeNs":"Deref"},"disambiguator":0},{"data":{"TypeNs":"Target"},"disambiguator":0}],"index":[2,2896]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"ops"},"disambiguator":0},{"data":{"TypeNs":"deref"},"disambiguator":0},{"data":{"TypeNs":"Deref"},"disambiguator":0},{"data":{"ValueNs":"deref"},"disambiguator":0},{"data":{"LifetimeNs":"'_"},"disambiguator":0}],"index":[2,51947]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"ops"},"disambiguator":0},{"data":{"TypeNs":"deref"},"disambiguator":0},{"data":{"TypeNs":"Deref"},"disambiguator":0},{"data":{"ValueNs":"deref"},"disambiguator":0}],"index":[2,2897]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"ops"},"disambiguator":0},{"data":{"TypeNs":"deref"},"disambiguator":0},{"data":{"TypeNs":"Deref"},"disambiguator":0}],"index":[2,2895]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"option"},"disambiguator":0},{"data":{"TypeNs":"Option"},"disambiguator":0},{"data":{"TypeNs":"None"},"disambiguator":0}],"index":[2,41364]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"option"},"disambiguator":0},{"data":{"TypeNs":"Option"},"disambiguator":0},{"data":{"TypeNs":"Some"},"disambiguator":0},{"data":{"ValueNs":"0"},"disambiguator":0}],"index":[2,41368]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"option"},"disambiguator":0},{"data":{"TypeNs":"Option"},"disambiguator":0},{"data":{"TypeNs":"Some"},"disambiguator":0}],"index":[2,41366]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"option"},"disambiguator":0},{"data":{"TypeNs":"Option"},"disambiguator":0}],"index":[2,41362]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"option"},"disambiguator":0}],"index":[2,41362]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"iter"},"disambiguator":0},{"data":{"TypeNs":"adapters"},"disambiguator":0},{"data":{"TypeNs":"map"},"disambiguator":0},{"data":{"TypeNs":"Map"},"disambiguator":0}],"index":[2,40335]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"iter"},"disambiguator":0},{"data":{"TypeNs":"range"},"disambiguator":0},{"data":"Impl","disambiguator":3}],"index":[2,6809]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"iter"},"disambiguator":0},{"data":{"TypeNs":"range"},"disambiguator":0},{"data":"Impl","disambiguator":34}],"index":[2,40512]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"iter"},"disambiguator":0},{"data":{"TypeNs":"traits"},"disambiguator":0},{"data":{"TypeNs":"iterator"},"disambiguator":0},{"data":{"TypeNs":"Iterator"},"disambiguator":0},{"data":{"TypeNs":"Item"},"disambiguator":0}],"index":[2,7316]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"iter"},"disambiguator":0},{"data":{"TypeNs":"traits"},"disambiguator":0},{"data":{"TypeNs":"iterator"},"disambiguator":0},{"data":{"TypeNs":"Iterator"},"disambiguator":0},{"data":{"ValueNs":"next"},"disambiguator":0},{"data":{"LifetimeNs":"'_"},"disambiguator":0}],"index":[2,53219]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"iter"},"disambiguator":0},{"data":{"TypeNs":"traits"},"disambiguator":0},{"data":{"TypeNs":"iterator"},"disambiguator":0},{"data":{"TypeNs":"Iterator"},"disambiguator":0},{"data":{"ValueNs":"next"},"disambiguator":0}],"index":[2,7317]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"iter"},"disambiguator":0},{"data":{"TypeNs":"traits"},"disambiguator":0},{"data":{"TypeNs":"iterator"},"disambiguator":0},{"data":{"TypeNs":"Iterator"},"disambiguator":0},{"data":{"ValueNs":"map"},"disambiguator":0}],"index":[2,7337]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"iter"},"disambiguator":0},{"data":{"TypeNs":"traits"},"disambiguator":0},{"data":{"TypeNs":"iterator"},"disambiguator":0},{"data":{"TypeNs":"Iterator"},"disambiguator":0}],"index":[2,7315]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"iter"},"disambiguator":0},{"data":{"TypeNs":"traits"},"disambiguator":0},{"data":{"TypeNs":"collect"},"disambiguator":0},{"data":"Impl","disambiguator":0}],"index":[2,7203]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"iter"},"disambiguator":0},{"data":{"TypeNs":"traits"},"disambiguator":0},{"data":{"TypeNs":"collect"},"disambiguator":0},{"data":{"TypeNs":"IntoIterator"},"disambiguator":0},{"data":{"TypeNs":"IntoIter"},"disambiguator":0}],"index":[2,7201]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"iter"},"disambiguator":0},{"data":{"TypeNs":"traits"},"disambiguator":0},{"data":{"TypeNs":"collect"},"disambiguator":0},{"data":{"TypeNs":"IntoIterator"},"disambiguator":0},{"data":{"ValueNs":"into_iter"},"disambiguator":0}],"index":[2,7202]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"iter"},"disambiguator":0},{"data":{"TypeNs":"traits"},"disambiguator":0},{"data":{"TypeNs":"collect"},"disambiguator":0},{"data":{"TypeNs":"IntoIterator"},"disambiguator":0}],"index":[2,7199]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"clone"},"disambiguator":0},{"data":{"TypeNs":"Clone"},"disambiguator":0},{"data":{"ValueNs":"clone"},"disambiguator":0},{"data":{"LifetimeNs":"'_"},"disambiguator":0}],"index":[2,51727]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"clone"},"disambiguator":0},{"data":{"TypeNs":"Clone"},"disambiguator":0},{"data":{"ValueNs":"clone"},"disambiguator":0}],"index":[2,2263]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"clone"},"disambiguator":0},{"data":{"TypeNs":"impls"},"disambiguator":0},{"data":"Impl","disambiguator":14}],"index":[2,30711]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"slice"},"disambiguator":0},{"data":{"TypeNs":"iter"},"disambiguator":0},{"data":{"TypeNs":"Iter"},"disambiguator":0}],"index":[2,9958]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"slice"},"disambiguator":0},{"data":{"TypeNs":"iter"},"disambiguator":0},{"data":"Impl","disambiguator":181}],"index":[2,42951]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"slice"},"disambiguator":0},{"data":"Impl","disambiguator":0},{"data":{"ValueNs":"iter"},"disambiguator":0},{"data":{"LifetimeNs":"'_"},"disambiguator":0}],"index":[2,54762]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"core","path":[{"data":{"TypeNs":"slice"},"disambiguator":0},{"data":"Impl","disambiguator":0},{"data":{"ValueNs":"iter"},"disambiguator":0}],"index":[2,11039]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"rust_primitives","path":[{"data":"Use","disambiguator":0}],"index":[0,1]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"rust_primitives","path":[{"data":{"TypeNs":"std"},"disambiguator":0}],"index":[0,2]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"rust_primitives","path":[{"data":{"TypeNs":"alloc"},"disambiguator":0}],"index":[0,3]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"std","path":[{"data":{"TypeNs":"prelude"},"disambiguator":0},{"data":{"TypeNs":"rust_2021"},"disambiguator":0}],"index":[1,134]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"std","path":[{"data":{"TypeNs":"prelude"},"disambiguator":0}],"index":[1,47]}|hax_generated_name});
    Hax_engine.Types.parse_def_id
      (Yojson.Safe.from_string
         {hax_generated_name|{"krate":"std","path":[],"index":[1,0]}|hax_generated_name});
  ]
