(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* From Core Require Import Core. *)

Class t_Index (v_Self : Type) (v_Idx : Type) : Type :=
  {
    Index_f_Output : Type;
    Index_f_index : v_Self -> v_Idx -> Index_f_Output;
  }.
Arguments t_Index (_) (_).
