(* File automatically generated by Hacspec *)
From Hacspec Require Import Hacspec_Lib MachineIntegers.
From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.

Require Import Super.
Export Super.

Definition abstract_concretize_cancel (x : t_U64_t) : unit :=
  tt.

Definition mod_add (x : t_U64_t) (y : t_U64_t) (z : t_U64_t) : unit :=
  tt.

Definition mod_mul (x : t_U64_t) (y : t_U64_t) (z : t_U64_t) : unit :=
  tt.

Definition mod_one (x : t_U64_t) : unit :=
  tt.

Definition mod_sub (x : t_U64_t) (y : t_U64_t) (z : t_U64_t) : unit :=
  tt.
