(* File automatically generated by Hacspec *)
From Hacspec Require Import Hacspec_Lib MachineIntegers.
From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.

Require Import fmt.
Export fmt.

Require Import Location.
Export Location.

Require Import PanicInfo.
Export PanicInfo.

Inductive t_AssertKind : Type :=
| AssertKind_Eq : t_AssertKind
| AssertKind_Ne : t_AssertKind
| AssertKind_Match : t_AssertKind.

Definition t_AssertKind_cast_to_repr (x : t_AssertKind_t) : uint_size :=
  match x with
  | AssertKind_Eq  =>
    (@repr WORDSIZE32 0)
  | AssertKind_Ne  =>
    (@repr WORDSIZE32 1)
  | AssertKind_Match  =>
    (@repr WORDSIZE32 3)
  end.

Inductive t_Never : Type :=
.

Definition t_Never_cast_to_repr (x : t_Never_t) : t_Never_t :=
  match x with
  
  end.

Definition never_to_any (x : t_Never_t) : T :=
  never_to_any match x with
  
  end.

Definition panic_fmt (fmt : t_Arguments_t) : t_Never_t :=
  panic_fmt fmt.

(*item error backend*)

Definition panic_display (x : T) : t_Never_t :=
  panic_fmt (impl_2__new_v1 (array_from_list []) (array_from_list [impl_1__new_display x])).

Definition panic_explicit (_ : unit) : t_Never_t :=
  panic_display explicit panic.
