(* File automatically generated by Hacspec *)
From Hacspec Require Import Hacspec_Lib MachineIntegers.
From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.

Require Import Super_Super_Haxint.
Export Super_Super_Haxint.

Require Import Super_Positive.
Export Super_Positive.

Inductive t_POS : Type :=
| POS_ZERO : t_POS
| POS_POS : t_Positive_t -> t_POS.

Definition match_pos (s : t_HaxInt_t) : t_POS_t :=
  if is_zero (f_clone s)
  then POS_ZEROt_POS_t
  else POS_POS (positive_from_int s).
