(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* From Core Require Import Core. *)

Class t_Clone (v_Self : Type) : Type :=
  {
    Clone_f_clone : v_Self -> v_Self;
  }.
Arguments t_Clone (_).

#[global] Instance t_Clone_any T : t_Clone T := { Clone_f_clone := id }.
