(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import String.

Class t_Clone `{v_Self : Type} : Type :=
  {
    t_Clone_f_clone : v_Self -> v_Self;
  }.
Arguments t_Clone:clear implicits.
Arguments t_Clone (_).
