(* File automatically generated by Hacspec *)
From Hacspec Require Import Hacspec_Lib MachineIntegers.
From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.

Require Import Tuple.
Export Tuple.

(*item error backend*)

Class t_FnMut (Self : _) := {
  f_call_mut : (Self -> Args -> Self × _) ;
}.

Class t_Fn (Self : _) := {
  f_call : (Self -> Args -> _) ;
}.

(*Not implemented yet? todo(item)*)
