(* File automatically generated by Hacspec *)
From Hacspec Require Import Hacspec_Lib MachineIntegers.
From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.

Require Import Slice.
Export Slice.

Require Import Iter.
Export Iter.

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

Definition impl__len (self : t_Slice_t T) : uint_size :=
  f_from (len (f_clone (f_v self))).

Definition impl__is_empty (self : t_Slice_t T) : bool :=
  eq (impl__len self) (@repr WORDSIZE32 0).

Definition impl__iter (self : t_Slice_t T) : t_Iter_t T :=
  impl__new self.
