(* File automatically generated by Hacspec *)
From Hacspec Require Import Hacspec_Lib MachineIntegers.
From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.

Require Import Crate_Base_interface_Int.
Export Crate_Base_interface_Int.

Require Import Crate_Primitive.
Export Crate_Primitive.

Require Import intrinsics.
Export intrinsics.

Require Import Index.
Export Index.

Require Import Crate_Base_Seq.
Export Crate_Base_Seq.

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

Definition impl_10__MAX : t_u128_t :=
  C_u128 f_MAX.

Definition impl_10__MIN : t_u128_t :=
  C_u128 f_MIN.

Definition impl_10__from_le (x : t_u128_t) : t_u128_t :=
  x.

Definition impl_10__to_le (self : t_u128_t) : t_u128_t :=
  self.

Definition impl_7__MAX : t_u16_t :=
  C_u16 f_MAX.

Definition impl_7__MIN : t_u16_t :=
  C_u16 f_MIN.

Definition impl_7__from_le (x : t_u16_t) : t_u16_t :=
  x.

Definition impl_7__to_le (self : t_u16_t) : t_u16_t :=
  self.

Definition impl__i8__BITS : t_u32_t :=
  C_u32 impl_97__BITS.

Definition impl__i16__BITS : t_u32_t :=
  C_u32 impl_83__BITS.

Definition impl__i32__BITS : t_u32_t :=
  C_u32 impl_69__BITS.

Definition impl__i64__BITS : t_u32_t :=
  C_u32 impl_55__BITS.

Definition impl__i128__BITS : t_u32_t :=
  C_u32 impl_41__BITS.

Definition impl__isize__BITS : t_u32_t :=
  C_u32 impl_55__BITS.

Definition impl_6__BITS : t_u32_t :=
  C_u32 impl_219__BITS.

Definition impl_7__BITS : t_u32_t :=
  C_u32 impl_192__BITS.

Definition impl_8__BITS : t_u32_t :=
  C_u32 impl_165__BITS.

Definition impl_8__MAX : t_u32_t :=
  C_u32 f_MAX.

Definition impl_8__MIN : t_u32_t :=
  C_u32 f_MIN.

Definition impl_8__from_le (x : t_u32_t) : t_u32_t :=
  x.

Definition impl_8__to_le (self : t_u32_t) : t_u32_t :=
  self.

Definition impl_9__BITS : t_u32_t :=
  C_u32 impl_138__BITS.

Definition impl_10__BITS : t_u32_t :=
  C_u32 impl_111__BITS.

Definition impl_11__BITS : t_u32_t :=
  C_u32 impl_138__BITS.

Definition impl_9__MAX : t_u64_t :=
  C_u64 f_MAX.

Definition impl_9__MIN : t_u64_t :=
  C_u64 f_MIN.

Definition impl_9__from_le (x : t_u64_t) : t_u64_t :=
  x.

Definition impl_9__to_le (self : t_u64_t) : t_u64_t :=
  self.

Definition impl_6__MAX : t_u8_t :=
  C_u8 f_MAX.

Definition impl_6__MIN : t_u8_t :=
  C_u8 f_MIN.

Definition impl_6__from_le (x : t_u8_t) : t_u8_t :=
  x.

Definition impl_6__to_le (self : t_u8_t) : t_u8_t :=
  self.

Definition impl_11__MAX : t_usize_t :=
  C_usize f_MAX.

Definition impl_11__MIN : t_usize_t :=
  C_usize f_MIN.

Definition impl_11__from_le (x : t_usize_t) : t_usize_t :=
  x.

Definition impl_11__to_le (self : t_usize_t) : t_usize_t :=
  self.

Definition impl_6__checked_add (self : t_u8_t) (rhs : t_u8_t) : t_Option_t t_u8_t :=
  Option_Some (unchecked_add_u8 self rhs).

Definition impl_7__checked_add (self : t_u16_t) (rhs : t_u16_t) : t_Option_t t_u16_t :=
  Option_Some (unchecked_add_u16 self rhs).

Definition impl_8__checked_add (self : t_u32_t) (rhs : t_u32_t) : t_Option_t t_u32_t :=
  Option_Some (unchecked_add_u32 self rhs).

Definition impl_9__checked_add (self : t_u64_t) (rhs : t_u64_t) : t_Option_t t_u64_t :=
  Option_Some (unchecked_add_u64 self rhs).

Definition impl_10__checked_add (self : t_u128_t) (rhs : t_u128_t) : t_Option_t t_u128_t :=
  Option_Some (unchecked_add_u128 self rhs).

Definition impl_11__checked_add (self : t_usize_t) (rhs : t_usize_t) : t_Option_t t_usize_t :=
  Option_Some (unchecked_add_usize self rhs).

Definition impl__i128__MAX : t_i128_t :=
  C_i128 f_MAX.

Definition impl__i128__MIN : t_i128_t :=
  C_i128 f_MIN.

Definition impl__i16__MAX : t_i16_t :=
  C_i16 f_MAX.

Definition impl__i16__MIN : t_i16_t :=
  C_i16 f_MIN.

Definition impl__i32__MAX : t_i32_t :=
  C_i32 f_MAX.

Definition impl__i32__MIN : t_i32_t :=
  C_i32 f_MIN.

Definition impl__i64__MAX : t_i64_t :=
  C_i64 f_MAX.

Definition impl__i64__MIN : t_i64_t :=
  C_i64 f_MIN.

Definition impl__i8__MAX : t_i8_t :=
  C_i8 f_MAX.

Definition impl__i8__MIN : t_i8_t :=
  C_i8 f_MIN.

Definition impl__isize__MAX : t_isize_t :=
  C_isize f_MAX.

Definition impl__isize__MIN : t_isize_t :=
  C_isize f_MIN.

Definition impl__i8__is_negative (self : t_i8_t) : bool :=
  self<.?(f_into (@repr WORDSIZE8 0)).

Definition impl__i8__is_positive (self : t_i8_t) : bool :=
  self>.?(f_into (@repr WORDSIZE8 0)).

Definition impl__i8__signum (self : t_i8_t) : t_i8_t :=
  if (f_clone self)<.?(f_into (@repr WORDSIZE8 0))
  then f_into (@repr WORDSIZE8 1)
  else if self=.?(f_into (@repr WORDSIZE8 0))
    then f_into (@repr WORDSIZE8 0)
    else f_into (@repr WORDSIZE8 1).

Definition impl__i16__is_negative (self : t_i16_t) : bool :=
  self<.?(f_into (@repr WORDSIZE16 0)).

Definition impl__i16__is_positive (self : t_i16_t) : bool :=
  self>.?(f_into (@repr WORDSIZE16 0)).

Definition impl__i16__signum (self : t_i16_t) : t_i16_t :=
  if (f_clone self)<.?(f_into (@repr WORDSIZE16 0))
  then f_into (@repr WORDSIZE16 1)
  else if self=.?(f_into (@repr WORDSIZE16 0))
    then f_into (@repr WORDSIZE16 0)
    else f_into (@repr WORDSIZE16 1).

Definition impl__i32__is_negative (self : t_i32_t) : bool :=
  self<.?(f_into (@repr WORDSIZE32 0)).

Definition impl__i32__is_positive (self : t_i32_t) : bool :=
  self>.?(f_into (@repr WORDSIZE32 0)).

Definition impl__i32__signum (self : t_i32_t) : t_i32_t :=
  if (f_clone self)<.?(f_into (@repr WORDSIZE32 0))
  then f_into (@repr WORDSIZE32 1)
  else if self=.?(f_into (@repr WORDSIZE32 0))
    then f_into (@repr WORDSIZE32 0)
    else f_into (@repr WORDSIZE32 1).

Definition impl__i64__is_negative (self : t_i64_t) : bool :=
  self<.?(f_into (@repr WORDSIZE64 0)).

Definition impl__i64__is_positive (self : t_i64_t) : bool :=
  self>.?(f_into (@repr WORDSIZE64 0)).

Definition impl__i64__signum (self : t_i64_t) : t_i64_t :=
  if (f_clone self)<.?(f_into (@repr WORDSIZE64 0))
  then f_into (@repr WORDSIZE64 1)
  else if self=.?(f_into (@repr WORDSIZE64 0))
    then f_into (@repr WORDSIZE64 0)
    else f_into (@repr WORDSIZE64 1).

Definition impl__i128__is_negative (self : t_i128_t) : bool :=
  self<.?(f_into (@repr WORDSIZE128 0)).

Definition impl__i128__is_positive (self : t_i128_t) : bool :=
  self>.?(f_into (@repr WORDSIZE128 0)).

Definition impl__i128__signum (self : t_i128_t) : t_i128_t :=
  if (f_clone self)<.?(f_into (@repr WORDSIZE128 0))
  then f_into (@repr WORDSIZE128 1)
  else if self=.?(f_into (@repr WORDSIZE128 0))
    then f_into (@repr WORDSIZE128 0)
    else f_into (@repr WORDSIZE128 1).

Definition impl__isize__is_negative (self : t_isize_t) : bool :=
  self<.?(f_into (@repr WORDSIZE32 0)).

Definition impl__isize__is_positive (self : t_isize_t) : bool :=
  self>.?(f_into (@repr WORDSIZE32 0)).

Definition impl__isize__signum (self : t_isize_t) : t_isize_t :=
  if (f_clone self)<.?(f_into (@repr WORDSIZE32 0))
  then f_into (@repr WORDSIZE32 1)
  else if self=.?(f_into (@repr WORDSIZE32 0))
    then f_into (@repr WORDSIZE32 0)
    else f_into (@repr WORDSIZE32 1).

Definition impl__i8__wrapping_add (self : t_i8_t) (rhs : t_i8_t) : t_i8_t :=
  wrapping_add_i8 self rhs.

Definition impl__i8__wrapping_sub (self : t_i8_t) (rhs : t_i8_t) : t_i8_t :=
  wrapping_sub_i8 self rhs.

Definition impl__i8__wrapping_neg (self : t_i8_t) : t_i8_t :=
  impl__i8__wrapping_sub (f_into (@repr WORDSIZE8 0)) self.

Definition impl__i8__wrapping_abs (self : t_i8_t) : t_i8_t :=
  if impl__i8__is_negative (f_clone self)
  then impl__i8__wrapping_neg self
  else self.

Definition impl__i16__wrapping_add (self : t_i16_t) (rhs : t_i16_t) : t_i16_t :=
  wrapping_add_i16 self rhs.

Definition impl__i16__wrapping_sub (self : t_i16_t) (rhs : t_i16_t) : t_i16_t :=
  wrapping_sub_i16 self rhs.

Definition impl__i16__wrapping_neg (self : t_i16_t) : t_i16_t :=
  impl__i16__wrapping_sub (f_into (@repr WORDSIZE16 0)) self.

Definition impl__i16__wrapping_abs (self : t_i16_t) : t_i16_t :=
  if impl__i16__is_negative (f_clone self)
  then impl__i16__wrapping_neg self
  else self.

Definition impl__i32__wrapping_add (self : t_i32_t) (rhs : t_i32_t) : t_i32_t :=
  wrapping_add_i32 self rhs.

Definition impl__i32__wrapping_sub (self : t_i32_t) (rhs : t_i32_t) : t_i32_t :=
  wrapping_sub_i32 self rhs.

Definition impl__i32__wrapping_neg (self : t_i32_t) : t_i32_t :=
  impl__i32__wrapping_sub (f_into (@repr WORDSIZE32 0)) self.

Definition impl__i32__wrapping_abs (self : t_i32_t) : t_i32_t :=
  if impl__i32__is_negative (f_clone self)
  then impl__i32__wrapping_neg self
  else self.

Definition impl__i64__wrapping_add (self : t_i64_t) (rhs : t_i64_t) : t_i64_t :=
  wrapping_add_i64 self rhs.

Definition impl__i64__wrapping_sub (self : t_i64_t) (rhs : t_i64_t) : t_i64_t :=
  wrapping_sub_i64 self rhs.

Definition impl__i64__wrapping_neg (self : t_i64_t) : t_i64_t :=
  impl__i64__wrapping_sub (f_into (@repr WORDSIZE64 0)) self.

Definition impl__i64__wrapping_abs (self : t_i64_t) : t_i64_t :=
  if impl__i64__is_negative (f_clone self)
  then impl__i64__wrapping_neg self
  else self.

Definition impl__i128__wrapping_add (self : t_i128_t) (rhs : t_i128_t) : t_i128_t :=
  wrapping_add_i128 self rhs.

Definition impl__i128__wrapping_sub (self : t_i128_t) (rhs : t_i128_t) : t_i128_t :=
  wrapping_sub_i128 self rhs.

Definition impl__i128__wrapping_neg (self : t_i128_t) : t_i128_t :=
  impl__i128__wrapping_sub (f_into (@repr WORDSIZE128 0)) self.

Definition impl__i128__wrapping_abs (self : t_i128_t) : t_i128_t :=
  if impl__i128__is_negative (f_clone self)
  then impl__i128__wrapping_neg self
  else self.

Definition impl__isize__wrapping_add (self : t_isize_t) (rhs : t_isize_t) : t_isize_t :=
  wrapping_add_isize self rhs.

Definition impl__isize__wrapping_sub (self : t_isize_t) (rhs : t_isize_t) : t_isize_t :=
  wrapping_sub_isize self rhs.

Definition impl__isize__wrapping_neg (self : t_isize_t) : t_isize_t :=
  impl__isize__wrapping_sub (f_into (@repr WORDSIZE32 0)) self.

Definition impl__isize__wrapping_abs (self : t_isize_t) : t_isize_t :=
  if impl__isize__is_negative (f_clone self)
  then impl__isize__wrapping_neg self
  else self.

Definition impl_6__checked_div (self : t_u8_t) (rhs : t_u8_t) : t_Option_t t_u8_t :=
  if rhs=.?(f_into (@repr WORDSIZE8 0))
  then Option_Nonet_Option_t t_u8_t
  else Option_Some (unchecked_div_u8 self rhs).

Definition impl_6__overflowing_add (self : t_u8_t) (rhs : t_u8_t) : t_u8_t × bool :=
  add_with_overflow_u8 self rhs.

Definition impl_7__checked_div (self : t_u16_t) (rhs : t_u16_t) : t_Option_t t_u16_t :=
  if rhs=.?(f_into (@repr WORDSIZE16 0))
  then Option_Nonet_Option_t t_u16_t
  else Option_Some (unchecked_div_u16 self rhs).

Definition impl_7__overflowing_add (self : t_u16_t) (rhs : t_u16_t) : t_u16_t × bool :=
  add_with_overflow_u16 self rhs.

Definition impl_8__checked_div (self : t_u32_t) (rhs : t_u32_t) : t_Option_t t_u32_t :=
  if rhs=.?(f_into (@repr WORDSIZE32 0))
  then Option_Nonet_Option_t t_u32_t
  else Option_Some (unchecked_div_u32 self rhs).

Definition impl_8__overflowing_add (self : t_u32_t) (rhs : t_u32_t) : t_u32_t × bool :=
  add_with_overflow_u32 self rhs.

Definition impl_9__checked_div (self : t_u64_t) (rhs : t_u64_t) : t_Option_t t_u64_t :=
  if rhs=.?(f_into (@repr WORDSIZE64 0))
  then Option_Nonet_Option_t t_u64_t
  else Option_Some (unchecked_div_u64 self rhs).

Definition impl_9__overflowing_add (self : t_u64_t) (rhs : t_u64_t) : t_u64_t × bool :=
  add_with_overflow_u64 self rhs.

Definition impl_10__checked_div (self : t_u128_t) (rhs : t_u128_t) : t_Option_t t_u128_t :=
  if rhs=.?(f_into (@repr WORDSIZE128 0))
  then Option_Nonet_Option_t t_u128_t
  else Option_Some (unchecked_div_u128 self rhs).

Definition impl_10__overflowing_add (self : t_u128_t) (rhs : t_u128_t) : t_u128_t × bool :=
  add_with_overflow_u128 self rhs.

Definition impl_11__checked_div (self : t_usize_t) (rhs : t_usize_t) : t_Option_t t_usize_t :=
  if rhs=.?(f_into (@repr WORDSIZE32 0))
  then Option_Nonet_Option_t t_usize_t
  else Option_Some (unchecked_div_usize self rhs).

Definition impl_11__overflowing_add (self : t_usize_t) (rhs : t_usize_t) : t_usize_t × bool :=
  add_with_overflow_usize self rhs.

Definition impl_6__wrapping_add (self : t_u8_t) (rhs : t_u8_t) : t_u8_t :=
  wrapping_add_u8 self rhs.

Definition impl_6__wrapping_mul (self : t_u8_t) (rhs : t_u8_t) : t_u8_t :=
  wrapping_mul_u8 self rhs.

Definition impl_7__wrapping_add (self : t_u16_t) (rhs : t_u16_t) : t_u16_t :=
  wrapping_add_u16 self rhs.

Definition impl_7__wrapping_mul (self : t_u16_t) (rhs : t_u16_t) : t_u16_t :=
  wrapping_mul_u16 self rhs.

Definition impl_8__wrapping_add (self : t_u32_t) (rhs : t_u32_t) : t_u32_t :=
  wrapping_add_u32 self rhs.

Definition impl_8__wrapping_mul (self : t_u32_t) (rhs : t_u32_t) : t_u32_t :=
  wrapping_mul_u32 self rhs.

Definition impl_9__wrapping_add (self : t_u64_t) (rhs : t_u64_t) : t_u64_t :=
  wrapping_add_u64 self rhs.

Definition impl_9__wrapping_mul (self : t_u64_t) (rhs : t_u64_t) : t_u64_t :=
  wrapping_mul_u64 self rhs.

Definition impl_10__wrapping_add (self : t_u128_t) (rhs : t_u128_t) : t_u128_t :=
  wrapping_add_u128 self rhs.

Definition impl_10__wrapping_mul (self : t_u128_t) (rhs : t_u128_t) : t_u128_t :=
  wrapping_mul_u128 self rhs.

Definition impl_11__wrapping_add (self : t_usize_t) (rhs : t_usize_t) : t_usize_t :=
  wrapping_add_usize self rhs.

Definition impl_11__wrapping_mul (self : t_usize_t) (rhs : t_usize_t) : t_usize_t :=
  wrapping_mul_usize self rhs.

Definition impl__i8__abs (self : t_i8_t) : t_i8_t :=
  if impl__i8__is_negative (f_clone self)
  then f_neg self
  else self.

Definition impl__i16__abs (self : t_i16_t) : t_i16_t :=
  if impl__i16__is_negative (f_clone self)
  then f_neg self
  else self.

Definition impl__i32__abs (self : t_i32_t) : t_i32_t :=
  if impl__i32__is_negative (f_clone self)
  then f_neg self
  else self.

Definition impl__i64__abs (self : t_i64_t) : t_i64_t :=
  if impl__i64__is_negative (f_clone self)
  then f_neg self
  else self.

Definition impl__i128__abs (self : t_i128_t) : t_i128_t :=
  if impl__i128__is_negative (f_clone self)
  then f_neg self
  else self.

Definition impl__isize__abs (self : t_isize_t) : t_isize_t :=
  if impl__isize__is_negative (f_clone self)
  then f_neg self
  else self.

Definition impl_6__wrapping_sub (self : t_u8_t) (rhs : t_u8_t) : t_u8_t :=
  wrapping_sub_u8 self rhs.

Definition impl_6__wrapping_neg (self : t_u8_t) : t_u8_t :=
  impl_6__wrapping_sub (C_u8 f_ZERO) self.

Definition impl_7__wrapping_sub (self : t_u16_t) (rhs : t_u16_t) : t_u16_t :=
  wrapping_sub_u16 self rhs.

Definition impl_7__wrapping_neg (self : t_u16_t) : t_u16_t :=
  impl_7__wrapping_sub (C_u16 f_ZERO) self.

Definition impl_8__wrapping_sub (self : t_u32_t) (rhs : t_u32_t) : t_u32_t :=
  wrapping_sub_u32 self rhs.

Definition impl_8__wrapping_neg (self : t_u32_t) : t_u32_t :=
  impl_8__wrapping_sub (C_u32 f_ZERO) self.

Definition impl_9__wrapping_sub (self : t_u64_t) (rhs : t_u64_t) : t_u64_t :=
  wrapping_sub_u64 self rhs.

Definition impl_9__wrapping_neg (self : t_u64_t) : t_u64_t :=
  impl_9__wrapping_sub (C_u64 f_ZERO) self.

Definition impl_10__wrapping_sub (self : t_u128_t) (rhs : t_u128_t) : t_u128_t :=
  wrapping_sub_u128 self rhs.

Definition impl_10__wrapping_neg (self : t_u128_t) : t_u128_t :=
  impl_10__wrapping_sub (C_u128 f_ZERO) self.

Definition impl_11__wrapping_sub (self : t_usize_t) (rhs : t_usize_t) : t_usize_t :=
  wrapping_sub_usize self rhs.

Definition impl_11__wrapping_neg (self : t_usize_t) : t_usize_t :=
  impl_11__wrapping_sub (C_usize f_ZERO) self.

Definition impl_6__wrapping_div (self : t_u8_t) (rhs : t_u8_t) : t_u8_t :=
  self./rhs.

Definition impl_6__wrapping_div_euclid (self : t_u8_t) (rhs : t_u8_t) : t_u8_t :=
  self./rhs.

Definition impl_7__wrapping_div (self : t_u16_t) (rhs : t_u16_t) : t_u16_t :=
  self./rhs.

Definition impl_7__wrapping_div_euclid (self : t_u16_t) (rhs : t_u16_t) : t_u16_t :=
  self./rhs.

Definition impl_8__wrapping_div (self : t_u32_t) (rhs : t_u32_t) : t_u32_t :=
  self./rhs.

Definition impl_8__wrapping_div_euclid (self : t_u32_t) (rhs : t_u32_t) : t_u32_t :=
  self./rhs.

Definition impl_9__wrapping_div (self : t_u64_t) (rhs : t_u64_t) : t_u64_t :=
  self./rhs.

Definition impl_9__wrapping_div_euclid (self : t_u64_t) (rhs : t_u64_t) : t_u64_t :=
  self./rhs.

Definition impl_10__wrapping_div (self : t_u128_t) (rhs : t_u128_t) : t_u128_t :=
  self./rhs.

Definition impl_10__wrapping_div_euclid (self : t_u128_t) (rhs : t_u128_t) : t_u128_t :=
  self./rhs.

Definition impl_11__wrapping_div (self : t_usize_t) (rhs : t_usize_t) : t_usize_t :=
  self./rhs.

Definition impl_11__wrapping_div_euclid (self : t_usize_t) (rhs : t_usize_t) : t_usize_t :=
  self./rhs.

Definition impl_6__wrapping_rem (self : t_u8_t) (rhs : t_u8_t) : t_u8_t :=
  self.%rhs.

Definition impl_6__wrapping_rem_euclid (self : t_u8_t) (rhs : t_u8_t) : t_u8_t :=
  self.%rhs.

Definition impl_7__wrapping_rem (self : t_u16_t) (rhs : t_u16_t) : t_u16_t :=
  self.%rhs.

Definition impl_7__wrapping_rem_euclid (self : t_u16_t) (rhs : t_u16_t) : t_u16_t :=
  self.%rhs.

Definition impl_8__wrapping_rem (self : t_u32_t) (rhs : t_u32_t) : t_u32_t :=
  self.%rhs.

Definition impl_8__wrapping_rem_euclid (self : t_u32_t) (rhs : t_u32_t) : t_u32_t :=
  self.%rhs.

Definition impl_9__wrapping_rem (self : t_u64_t) (rhs : t_u64_t) : t_u64_t :=
  self.%rhs.

Definition impl_9__wrapping_rem_euclid (self : t_u64_t) (rhs : t_u64_t) : t_u64_t :=
  self.%rhs.

Definition impl_10__wrapping_rem (self : t_u128_t) (rhs : t_u128_t) : t_u128_t :=
  self.%rhs.

Definition impl_10__wrapping_rem_euclid (self : t_u128_t) (rhs : t_u128_t) : t_u128_t :=
  self.%rhs.

Definition impl_11__wrapping_rem (self : t_usize_t) (rhs : t_usize_t) : t_usize_t :=
  self.%rhs.

Definition impl_11__wrapping_rem_euclid (self : t_usize_t) (rhs : t_usize_t) : t_usize_t :=
  self.%rhs.

Definition impl_6__rotate_left (self : t_u8_t) (n : t_u32_t) : t_u8_t :=
  run (let hoist1 := ControlFlow_Break (rotate_left_u8 self n) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist1)).

Definition impl_6__rotate_right (self : t_u8_t) (n : t_u32_t) : t_u8_t :=
  run (let hoist2 := ControlFlow_Break (rotate_right_u8 self n) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist2)).

Definition impl_7__rotate_left (self : t_u16_t) (n : t_u32_t) : t_u16_t :=
  run (let hoist3 := ControlFlow_Break (rotate_left_u16 self n) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist3)).

Definition impl_7__rotate_right (self : t_u16_t) (n : t_u32_t) : t_u16_t :=
  run (let hoist4 := ControlFlow_Break (rotate_right_u16 self n) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist4)).

Definition impl_8__rotate_left (self : t_u32_t) (n : t_u32_t) : t_u32_t :=
  run (let hoist5 := ControlFlow_Break (rotate_left_u32 self n) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist5)).

Definition impl_8__rotate_right (self : t_u32_t) (n : t_u32_t) : t_u32_t :=
  run (let hoist6 := ControlFlow_Break (rotate_right_u32 self n) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist6)).

Definition impl_9__rotate_left (self : t_u64_t) (n : t_u32_t) : t_u64_t :=
  run (let hoist7 := ControlFlow_Break (rotate_left_u64 self n) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist7)).

Definition impl_9__rotate_right (self : t_u64_t) (n : t_u32_t) : t_u64_t :=
  run (let hoist8 := ControlFlow_Break (rotate_right_u64 self n) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist8)).

Definition impl_10__rotate_left (self : t_u128_t) (n : t_u32_t) : t_u128_t :=
  run (let hoist9 := ControlFlow_Break (rotate_left_u128 self n) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist9)).

Definition impl_10__rotate_right (self : t_u128_t) (n : t_u32_t) : t_u128_t :=
  run (let hoist10 := ControlFlow_Break (rotate_right_u128 self n) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist10)).

Definition impl_11__rotate_left (self : t_usize_t) (n : t_u32_t) : t_usize_t :=
  run (let hoist11 := ControlFlow_Break (rotate_left_usize self n) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist11)).

Definition impl_11__rotate_right (self : t_usize_t) (n : t_u32_t) : t_usize_t :=
  run (let hoist12 := ControlFlow_Break (rotate_right_usize self n) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist12)).

Definition impl_6__count_ones (self : t_u8_t) : t_u32_t :=
  run (let hoist13 := ControlFlow_Break (ctpop_u8 self) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist13)).

Definition impl_6__leading_zeros (self : t_u8_t) : t_u32_t :=
  run (let hoist14 := ControlFlow_Break (ctlz_u8 self) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist14)).

Definition impl_6__swap_bytes (self : t_u8_t) : t_u8_t :=
  f_into (bswap_u8 self).

Definition impl_6__from_be (x : t_u8_t) : t_u8_t :=
  impl_6__swap_bytes x.

Definition impl_6__to_be (self : t_u8_t) : t_u8_t :=
  impl_6__swap_bytes self.

Definition impl_6__trailing_zeros (self : t_u8_t) : t_u32_t :=
  run (let hoist15 := ControlFlow_Break (cttz_u8 self) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist15)).

Definition impl_7__count_ones (self : t_u16_t) : t_u32_t :=
  run (let hoist16 := ControlFlow_Break (ctpop_u16 self) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist16)).

Definition impl_7__leading_zeros (self : t_u16_t) : t_u32_t :=
  run (let hoist17 := ControlFlow_Break (ctlz_u16 self) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist17)).

Definition impl_7__swap_bytes (self : t_u16_t) : t_u16_t :=
  f_into (bswap_u16 self).

Definition impl_7__from_be (x : t_u16_t) : t_u16_t :=
  impl_7__swap_bytes x.

Definition impl_7__to_be (self : t_u16_t) : t_u16_t :=
  impl_7__swap_bytes self.

Definition impl_7__trailing_zeros (self : t_u16_t) : t_u32_t :=
  run (let hoist18 := ControlFlow_Break (cttz_u16 self) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist18)).

Definition impl_8__count_ones (self : t_u32_t) : t_u32_t :=
  run (let hoist19 := ControlFlow_Break (ctpop_u32 self) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist19)).

Definition impl_8__leading_zeros (self : t_u32_t) : t_u32_t :=
  run (let hoist20 := ControlFlow_Break (ctlz_u32 self) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist20)).

Definition impl_8__swap_bytes (self : t_u32_t) : t_u32_t :=
  f_into (bswap_u32 self).

Definition impl_8__from_be (x : t_u32_t) : t_u32_t :=
  impl_8__swap_bytes x.

Definition impl_8__to_be (self : t_u32_t) : t_u32_t :=
  impl_8__swap_bytes self.

Definition impl_8__trailing_zeros (self : t_u32_t) : t_u32_t :=
  run (let hoist21 := ControlFlow_Break (cttz_u32 self) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist21)).

Definition impl_9__count_ones (self : t_u64_t) : t_u32_t :=
  run (let hoist22 := ControlFlow_Break (ctpop_u64 self) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist22)).

Definition impl_9__leading_zeros (self : t_u64_t) : t_u32_t :=
  run (let hoist23 := ControlFlow_Break (ctlz_u64 self) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist23)).

Definition impl_9__swap_bytes (self : t_u64_t) : t_u64_t :=
  f_into (bswap_u64 self).

Definition impl_9__from_be (x : t_u64_t) : t_u64_t :=
  impl_9__swap_bytes x.

Definition impl_9__to_be (self : t_u64_t) : t_u64_t :=
  impl_9__swap_bytes self.

Definition impl_9__trailing_zeros (self : t_u64_t) : t_u32_t :=
  run (let hoist24 := ControlFlow_Break (cttz_u64 self) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist24)).

Definition impl_10__count_ones (self : t_u128_t) : t_u32_t :=
  run (let hoist25 := ControlFlow_Break (ctpop_u128 self) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist25)).

Definition impl_10__leading_zeros (self : t_u128_t) : t_u32_t :=
  run (let hoist26 := ControlFlow_Break (ctlz_u128 self) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist26)).

Definition impl_10__swap_bytes (self : t_u128_t) : t_u128_t :=
  f_into (bswap_u128 self).

Definition impl_10__from_be (x : t_u128_t) : t_u128_t :=
  impl_10__swap_bytes x.

Definition impl_10__to_be (self : t_u128_t) : t_u128_t :=
  impl_10__swap_bytes self.

Definition impl_10__trailing_zeros (self : t_u128_t) : t_u32_t :=
  run (let hoist27 := ControlFlow_Break (cttz_u128 self) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist27)).

Definition impl_11__count_ones (self : t_usize_t) : t_u32_t :=
  run (let hoist28 := ControlFlow_Break (ctpop_usize self) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist28)).

Definition impl_11__leading_zeros (self : t_usize_t) : t_u32_t :=
  run (let hoist29 := ControlFlow_Break (ctlz_usize self) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist29)).

Definition impl_11__swap_bytes (self : t_usize_t) : t_usize_t :=
  f_into (bswap_usize self).

Definition impl_11__from_be (x : t_usize_t) : t_usize_t :=
  impl_11__swap_bytes x.

Definition impl_11__to_be (self : t_usize_t) : t_usize_t :=
  impl_11__swap_bytes self.

Definition impl_11__trailing_zeros (self : t_usize_t) : t_u32_t :=
  run (let hoist30 := ControlFlow_Break (cttz_usize self) : t_Never_t in
  ControlFlow_Continue (never_to_any hoist30)).

Definition impl__i8__rem_euclid (self : t_i8_t) (rhs : t_i8_t) : t_i8_t :=
  let r := self.%(f_clone rhs) : t_i8_t in
  if r<.?(f_into (@repr WORDSIZE8 0))
  then impl__i8__wrapping_add r (impl__i8__wrapping_abs rhs)
  else r.

Definition impl__i16__rem_euclid (self : t_i16_t) (rhs : t_i16_t) : t_i16_t :=
  let r := self.%(f_clone rhs) : t_i16_t in
  if r<.?(f_into (@repr WORDSIZE16 0))
  then impl__i16__wrapping_add r (impl__i16__wrapping_abs rhs)
  else r.

Definition impl__i32__rem_euclid (self : t_i32_t) (rhs : t_i32_t) : t_i32_t :=
  let r := self.%(f_clone rhs) : t_i32_t in
  if r<.?(f_into (@repr WORDSIZE32 0))
  then impl__i32__wrapping_add r (impl__i32__wrapping_abs rhs)
  else r.

Definition impl__i64__rem_euclid (self : t_i64_t) (rhs : t_i64_t) : t_i64_t :=
  let r := self.%(f_clone rhs) : t_i64_t in
  if r<.?(f_into (@repr WORDSIZE64 0))
  then impl__i64__wrapping_add r (impl__i64__wrapping_abs rhs)
  else r.

Definition impl__i128__rem_euclid (self : t_i128_t) (rhs : t_i128_t) : t_i128_t :=
  let r := self.%(f_clone rhs) : t_i128_t in
  if r<.?(f_into (@repr WORDSIZE128 0))
  then impl__i128__wrapping_add r (impl__i128__wrapping_abs rhs)
  else r.

Definition impl__isize__rem_euclid (self : t_isize_t) (rhs : t_isize_t) : t_isize_t :=
  let r := self.%(f_clone rhs) : t_isize_t in
  if r<.?(f_into (@repr WORDSIZE32 0))
  then impl__isize__wrapping_add r (impl__isize__wrapping_abs rhs)
  else r.

Definition impl_6__count_zeros (self : t_u8_t) : t_u32_t :=
  impl_6__count_ones (f_not self).

Definition impl_6__leading_ones (self : t_u8_t) : t_u32_t :=
  impl_6__leading_zeros (f_not self).

Definition impl_6__trailing_ones (self : t_u8_t) : t_u32_t :=
  impl_6__trailing_zeros (f_not self).

Definition impl_7__count_zeros (self : t_u16_t) : t_u32_t :=
  impl_7__count_ones (f_not self).

Definition impl_7__leading_ones (self : t_u16_t) : t_u32_t :=
  impl_7__leading_zeros (f_not self).

Definition impl_7__trailing_ones (self : t_u16_t) : t_u32_t :=
  impl_7__trailing_zeros (f_not self).

Definition impl_8__count_zeros (self : t_u32_t) : t_u32_t :=
  impl_8__count_ones (f_not self).

Definition impl_8__leading_ones (self : t_u32_t) : t_u32_t :=
  impl_8__leading_zeros (f_not self).

Definition impl_8__trailing_ones (self : t_u32_t) : t_u32_t :=
  impl_8__trailing_zeros (f_not self).

Definition impl_9__count_zeros (self : t_u64_t) : t_u32_t :=
  impl_9__count_ones (f_not self).

Definition impl_9__leading_ones (self : t_u64_t) : t_u32_t :=
  impl_9__leading_zeros (f_not self).

Definition impl_9__trailing_ones (self : t_u64_t) : t_u32_t :=
  impl_9__trailing_zeros (f_not self).

Definition impl_10__count_zeros (self : t_u128_t) : t_u32_t :=
  impl_10__count_ones (f_not self).

Definition impl_10__leading_ones (self : t_u128_t) : t_u32_t :=
  impl_10__leading_zeros (f_not self).

Definition impl_10__trailing_ones (self : t_u128_t) : t_u32_t :=
  impl_10__trailing_zeros (f_not self).

Definition impl_11__count_zeros (self : t_usize_t) : t_u32_t :=
  impl_11__count_ones (f_not self).

Definition impl_11__leading_ones (self : t_usize_t) : t_u32_t :=
  impl_11__leading_zeros (f_not self).

Definition impl_11__trailing_ones (self : t_usize_t) : t_u32_t :=
  impl_11__trailing_zeros (f_not self).
