(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import String.

Class t_Concretization `{v_Self : Type} `{v_T : Type} : Type :=
  {
    t_Concretization_f_concretize : v_Self -> v_T;
  }.
Arguments t_Concretization:clear implicits.
Arguments t_Concretization (_) (_).

Class t_Abstraction `{v_Self : Type} : Type :=
  {
    t_Abstraction_f_AbstractType : Type;
    t_Abstraction_f_lift : v_Self -> t_Abstraction_f_AbstractType;
  }.
Arguments t_Abstraction:clear implicits.
Arguments t_Abstraction (_).
