module FreshNamespace : module type of Concrete_ident_fresh_ns

module T : sig
  type t [@@deriving show, yojson, compare, sexp, eq, hash]
end

include module type of T with type t = T.t

type name = Concrete_ident_generated.t
[@@deriving show, yojson, compare, sexp, eq, hash]

type reserved_suffix = [ `Cast | `Pre | `Post ]
[@@deriving show, yojson, hash, compare, sexp, hash, eq]

val of_def_id :
  ?suffix:reserved_suffix option -> value:bool -> Types.def_id -> t

val of_name : value:bool -> name -> t
val eq_name : name -> t -> bool
val to_debug_string : t -> string
val fresh_namespace : t list -> string list -> FreshNamespace.t
val move_to_fresh_namespace : t -> FreshNamespace.t -> t
val with_suffix : reserved_suffix -> t -> t

(* module Create : sig
     val fresh_module : from:t list -> t
     val move_under : new_parent:t -> t -> t

     val constructor : t -> t
     (** [constructor ident] adds a [Ctor] to [ident]
         this allows to build a constructor from a variant name. *)

     val map_last : f:(string -> string) -> t -> t
     (** [map_last f ident] applies [f] on the last chunk of [ident]'s
         path if it holds a string *)
   end *)

(* type view = { crate : string; path : string list; definition : string }

   val map_path_strings : f:(string -> string) -> t -> t
   val matches_namespace : Types.namespace -> t -> bool

   include module type of struct
     include Concrete_ident_sig.Make (struct
       type t_ = t
       type view_ = view
     end)
   end

   module MakeViewAPI (NP : NAME_POLICY) : VIEW_API
   module DefaultNamePolicy : NAME_POLICY
   module DefaultViewAPI : VIEW_API *)

type comparator_witness

val comparator : (t, comparator_witness) Base.Comparator.comparator

module RenderSig : module type of Concrete_ident_render_sig.Make (T)

module type NAME_POLICY = Concrete_ident_render_sig.NAME_POLICY

module DefaultNamePolicy : NAME_POLICY
module MakeViewAPI (NP : NAME_POLICY) : RenderSig.RENDER_API

module ImplInfoStore : sig
  val init : (Types.def_id_contents * Types.impl_infos) list -> unit

  val lookup_raw : t -> Types.impl_infos option
  (** Lookup the (raw[1]) implementation informations given a concrete
  ident. Returns `Some _` if and only if the supplied identifier points
  to an `Impl`.
  
  [1]: those are raw THIR types.
  
  {b WARNING}: due to {{: https://github.com/hacspec/hax/issues/363}
  issue 363}, when looking up certain identifiers generated by the
  engine, this function may return [None] even though the supplied
  identifier points to an [Impl] block. *)
end
