open Hax_engine
open Utils
open Base
open Coq_ast

include
  Backend.Make
    (struct
      open Features
      include Off
      include On.Slice
      include On.Monadic_binding
      include On.Macro
      include On.Construct_base
    end)
    (struct
      let backend = Diagnostics.Backend.Coq
    end)

module SubtypeToInputLanguage
    (FA : Features.T
            with type mutable_reference = Features.Off.mutable_reference
             and type continue = Features.Off.continue
             and type break = Features.Off.break
             and type mutable_reference = Features.Off.mutable_reference
             and type mutable_pointer = Features.Off.mutable_pointer
             and type mutable_variable = Features.Off.mutable_variable
             and type reference = Features.Off.reference
             and type raw_pointer = Features.Off.raw_pointer
             and type early_exit = Features.Off.early_exit
             and type question_mark = Features.Off.question_mark
             and type as_pattern = Features.Off.as_pattern
             and type lifetime = Features.Off.lifetime
             and type monadic_action = Features.Off.monadic_action
             and type arbitrary_lhs = Features.Off.arbitrary_lhs
             and type nontrivial_lhs = Features.Off.nontrivial_lhs
             and type loop = Features.Off.loop
             and type block = Features.Off.block
             and type for_loop = Features.Off.for_loop
             and type while_loop = Features.Off.while_loop
             and type for_index_loop = Features.Off.for_index_loop
             and type quote = Features.Off.quote
             and type state_passing_loop = Features.Off.state_passing_loop
             and type fold_like_loop = Features.Off.fold_like_loop
             and type dyn = Features.Off.dyn
             and type match_guard = Features.Off.match_guard
             and type trait_item_default = Features.Off.trait_item_default
             and type unsafe = Features.Off.unsafe) =
struct
  module FB = InputLanguage

  include
    Subtype.Make (FA) (FB)
      (struct
        module A = FA
        module B = FB
        include Features.SUBTYPE.Id
        include Features.SUBTYPE.On.Monadic_binding
        include Features.SUBTYPE.On.Construct_base
        include Features.SUBTYPE.On.Slice
        include Features.SUBTYPE.On.Macro
      end)

  let metadata = Phase_utils.Metadata.make (Reject (NotInBackendLang backend))
end

module AST = Ast.Make (InputLanguage)
module BackendOptions = Backend.UnitBackendOptions
open Ast
module CoqNamePolicy = Concrete_ident.DefaultNamePolicy
module U = Ast_utils.MakeWithNamePolicy (InputLanguage) (CoqNamePolicy)
open AST

module CoqLibrary : Library = struct
  module Notation = struct
    let int_repr (x : string) (i : string) : string =
      "(@repr" ^ " " ^ "WORDSIZE" ^ x ^ " " ^ i ^ ")"

    let type_str : string = "Type"
    let bool_str : string = "bool"
    let unit_str : string = "unit"
  end
end

module C = Coq (CoqLibrary)

module Context = struct
  type t = { current_namespace : string * string list }
end

let primitive_to_string (id : primitive_ident) : string =
  match id with
  | Deref -> "(TODO: Deref)" (* failwith "Deref" *)
  | Cast -> "cast" (* failwith "Cast" *)
  | LogicalOp op -> ( match op with And -> "andb" | Or -> "orb")

let hardcoded_coq_headers =
  "(* File automatically generated by Hacspec *)\n\
   From Coq Require Import ZArith.\n\
   Import List.ListNotations.\n\
   Open Scope Z_scope.\n\
   Open Scope bool_scope.\n\
   Require Import String.\n\
   Notation \"'projection_0'\" := id.\n\
   From Core Require Import Core_Marker.\n"

module Make
    (F : Features.T) (Default : sig
      val default : string -> string
    end) =
struct
  module AST = Ast.Make (F)
  open Ast.Make (F)
  module Base = Generic_printer.Make (F)
  open PPrint
  module U = Ast_utils.MakeWithNamePolicy (F) (CoqNamePolicy)

  let default_string_for s = "TODO: please implement the method `" ^ s ^ "`"
  let default_document_for = default_string_for >> string

  module CoqNotation = struct
    let definition_struct keyword n name generics params typ body =
      keyword ^^ space ^^ name ^^ (if PPrint.is_empty generics then empty else space ^^ generics) ^^ concat_map (fun x -> space ^^ x) params ^^ space ^^ colon ^^ space ^^ typ ^^ space ^^ string ":=" ^^ nest n (
        break 1 ^^ body
      ) ^^ dot

    let definition = definition_struct (string "Definition") 2
    let fixpoint = definition_struct (string "Fixpoint") 2
    let inductive = definition_struct (string "Inductive") 0
    let record = definition_struct (string "Record") 2
    let instance = definition_struct (string "Instance") 2
    let class_ = definition_struct (string "Class") 2
  end

  let pconcrete_ident (id : concrete_ident) : string =
    let id = U.Concrete_ident_view.to_view id in
    id.definition

  let pglobal_ident (id : global_ident) : string =
    match id with
    | `Concrete cid -> pconcrete_ident cid
    | `Projector (`Concrete cid) -> pconcrete_ident cid ^ "_ci"
    | `Primitive p_id -> primitive_to_string p_id
    | `TupleType _i -> "TODO (global ident) tuple type"
    | `TupleCons i -> "TODO (global ident) tuple cons: " ^ Int.to_string i
    | `Projector (`TupleField _) | `TupleField _ -> "TODO (global ident) tuple field"
    | _ -> .

  class printer =
    object
      inherit Base.base

      (* BEGIN GENERATED *)
      method arm ~arm ~span:_ =
        arm#p

      method arm' ~super:_ ~arm_pat ~body ~guard:_ =
        space ^^ arm_pat#p ^^ space ^^ string "=>" ^^ nest 2 (
          break 1 ^^ body#p
        )

      method attrs _x1 = default_document_for "attrs"

      method binding_mode_ByRef _x1 _x2 =
        default_document_for "binding_mode_ByRef"

      method binding_mode_ByValue = default_document_for "binding_mode_ByValue"
      method borrow_kind_Mut _x1 = default_document_for "borrow_kind_Mut"
      method borrow_kind_Shared = default_document_for "borrow_kind_Shared"
      method borrow_kind_Unique = default_document_for "borrow_kind_Unique"
      method common_array x1 = brackets (separate comma x1)

      method dyn_trait_goal ~trait:_ ~non_self_args:_ =
        default_document_for "dyn_trait_goal"

      method error_expr _x1 = default_document_for "error_expr"
      method error_item _x1 = default_document_for "error_item"
      method error_pat _x1 = default_document_for "error_pat"
      method expr ~e ~span:_ ~typ = e#p (* parens (e#p ^^ space ^^ colon ^^ space ^^ typ#p) *)

      method expr'_AddressOf ~super:_ ~mut:_ ~e:_ ~witness:_ =
        default_document_for "expr'_AddressOf"

      method expr'_App_application ~super:_ ~f ~args ~generics:_ =
        f#p ^^ concat_map (fun x -> space ^^ parens(x#p)) args

      method expr'_App_constant ~super:_ ~constant:_ ~generics:_ =
        default_document_for "expr'_App_constant"

      method expr'_App_field_projection ~super:_ ~field ~e =
        (new printer)#entrypoint_ty e#v.typ (* TODO: Name of struct should be made accessible here! *) ^^ !^"_" ^^ field#p ^^ space ^^ e#p
      (* TODO: Do nothing if is zero *)

      method expr'_App_tuple_projection ~super:_ ~size:_ ~nth:_ ~e:_ =
        default_document_for "expr'_App_tuple_projection"

      method expr'_Ascription ~super:_ ~e:_ ~typ:_ =
        default_document_for "expr'_Ascription"

      method expr'_Assign ~super:_ ~lhs:_ ~e:_ ~witness:_ =
        default_document_for "expr'_Assign"

      method expr'_Block ~super:_ ~e:_ ~safety_mode:_ ~witness:_ =
        default_document_for "expr'_Block"

      method expr'_Borrow ~super:_ ~kind:_ ~e:_ ~witness:_ =
        default_document_for "expr'_Borrow"

      method expr'_Break ~super:_ ~e:_ ~acc:_ ~label:_ ~witness:_ =
        default_document_for "expr'_Break"

      method expr'_Closure ~super:_ ~params:_ ~body:_ ~captures:_ =
        default_document_for "expr'_Closure"

      method expr'_Construct_inductive ~super:_ ~constructor ~is_record
          ~is_struct ~fields ~base:_ =
        if is_struct
        then
          if is_record
          then
            string "Build_t_" ^^ constructor#p ^^ concat_map (fun (ident, exp) -> space ^^ parens(exp#p)) fields
          else
            concat_map (fun (ident, exp) -> space ^^ parens(exp#p)) fields
        else
          (* default_document_for "expr'_Construct_inductive" *)
          constructor#p ^^ concat_map (fun (ident, exp) -> space ^^ parens(exp#p)) fields

      method expr'_Construct_tuple ~super:_ ~components =
        parens ( separate_map comma (fun x -> x#p) components )

      method expr'_Continue ~super:_ ~acc:_ ~label:_ ~witness:_ =
        default_document_for "expr'_Continue"

      method expr'_EffectAction ~super:_ ~action:_ ~argument:_ =
        default_document_for "expr'_EffectAction"

      method expr'_GlobalVar_concrete ~super:_ x2 =
        x2#p

      method expr'_GlobalVar_primitive ~super:_ x2 =
        string (primitive_to_string x2)

      method expr'_If ~super:_ ~cond ~then_ ~else_ =
        string "if" ^^ nest 2 (break 1 ^^ cond#p) ^^ break 1
        ^^ string "then" ^^ nest 2 (break 1 ^^ then_#p) ^^ break 1
        ^^ string "else" ^^ nest 2 (break 1 ^^
                                    match else_ with
                                    | Some x -> x#p
                                    | None -> string "tt")

      method expr'_Let ~super:_ ~monadic:_ ~lhs ~rhs ~body =
       string "let" ^^ space ^^ lhs#p ^^ space ^^ string ":=" ^^ space ^^ rhs#p ^^ space ^^ string "in" ^^ break 1 ^^ body#p

      method expr'_Literal ~super:_ x2 = x2#p
      method expr'_LocalVar ~super:_ x2 = x2#p

      method expr'_Loop ~super:_ ~body:_ ~kind:_ ~state:_ ~control_flow:_ ~label:_ ~witness:_ =
        default_document_for "expr'_Loop"

      method expr'_MacroInvokation ~super:_ ~macro:_ ~args:_ ~witness:_ =
        default_document_for "expr'_MacroInvokation"

      method expr'_Match ~super:_ ~scrutinee ~arms =
        string "match" ^^ space ^^ scrutinee#p ^^ space ^^ string "with" ^^ break 1
        ^^ concat_map (fun x -> string "|" ^^ space ^^ x#p ^^ break 1) arms
        ^^ string "end"

      method expr'_QuestionMark ~super:_ ~e:_ ~return_typ:_ ~witness:_ =
        default_document_for "expr'_QuestionMark"

      method expr'_Quote ~super:_ _x2 = default_document_for "expr'_Quote"

      method expr'_Return ~super:_ ~e:_ ~witness:_ =
        default_document_for "expr'_Return"

      method cf_kind_BreakOrReturn =
        default_document_for "cf_kind_BreakOrReturn"

      method cf_kind_BreakOnly = default_document_for "cf_kind_BreakOnly"
      method field_pat ~field:_ ~pat:_ = default_document_for "field_pat"

      method generic_constraint_GCLifetime _x1 _x2 =
        default_document_for "generic_constraint_GCLifetime"

      method generic_constraint_GCProjection _x1 =
        default_document_for "generic_constraint_GCProjection"

      method generic_constraint_GCType x1 =
        x1#p

      method generic_param ~ident ~span:_ ~attrs:_ ~kind:_ =
        ident#p

      method generic_param_kind_GPConst ~typ:_ =
        default_document_for "generic_param_kind_GPConst"

      method generic_param_kind_GPLifetime ~witness:_ =
        default_document_for "generic_param_kind_GPLifetime"

      method generic_param_kind_GPType =
        default_document_for "generic_param_kind_GPType"

      method generic_value_GConst x1 =
        x1#p

      method generic_value_GLifetime ~lt:_ ~witness:_ =
        default_document_for "generic_value_GLifetime"

      method generic_value_GType x1 = x1#p

      method generics ~params ~constraints =
        let params_document = separate_map space (fun x -> string "`" ^^ braces (x#p ^^ space ^^ colon ^^ space ^^ string "Type")) params in
        let constraints_document = separate_map space (fun x -> string "`" ^^ braces (x#p)) constraints in
        match List.length params, List.length constraints with
        | 0, 0 -> empty
        | _, 0 ->
          params_document
        | 0, _ ->
          constraints_document
        | _, _ ->
          params_document ^^ space ^^ constraints_document

      method guard ~guard:_ ~span:_ = default_document_for "guard"

      method guard'_IfLet ~super:_ ~lhs:_ ~rhs:_ ~witness:_ =
        default_document_for "guard'_IfLet"

      method impl_expr ~kind ~goal = goal#p

      method impl_expr_kind_Builtin _x1 =
        default_document_for "impl_expr_kind_Builtin"

      method impl_expr_kind_Concrete _x1 =
        default_document_for "impl_expr_kind_Concrete"

      method impl_expr_kind_Dyn = default_document_for "impl_expr_kind_Dyn"

      method impl_expr_kind_ImplApp ~impl:_ ~args:_ =
        default_document_for "impl_expr_kind_ImplApp"

      method impl_expr_kind_LocalBound ~id:_ =
        default_document_for "impl_expr_kind_LocalBound"

      method impl_expr_kind_Parent ~impl:_ ~ident:_ =
        default_document_for "impl_expr_kind_Parent"

      method impl_expr_kind_Projection ~impl:_ ~item:_ ~ident:_ =
        default_document_for "impl_expr_kind_Projection"

      method impl_expr_kind_Self = default_document_for "impl_expr_kind_Self"
      method impl_ident ~goal ~name:_ =
        goal#p
      (* string name ^^ space ^^ colon ^^ space ^^ goal#p *)
      (* TODO: include names and do something about numbered names of instance *)

      method impl_item ~ii_span:_ ~ii_generics:_ ~ii_v ~ii_ident ~ii_attrs:_ =
        ii_ident#p ^^ space ^^ string ":=" ^^ space ^^ ii_v#p ^^ semi

      method impl_item'_IIFn ~body ~params =
        if List.length params == 0
        then body#p
        else
          string "fun" ^^ space ^^ (concat_map (fun x -> x#p ^^ space) params) ^^ string "=>" ^^ nest 2 (
            break 1 ^^ body#p
          )

      method impl_item'_IIType ~typ ~parent_bounds:_ =
        typ#p

      method item ~v ~span:_ ~ident:_ ~attrs:_ = v#p ^^ break 1

      method item'_Alias ~super:_ ~name:_ ~item:_ =
        default_document_for "item'_Alias"

      method item'_Fn ~super:_ ~name ~generics ~body ~params ~safety:_ =
        let is_rec =
          Set.mem
            (U.Reducers.collect_concrete_idents#visit_expr () body#v)
            name#v
        in
        let typ = (new printer)#entrypoint_ty body#v.typ in
        if is_rec
        then
          CoqNotation.fixpoint (name#p) generics#p (List.map ~f:(fun x -> x#p) params) typ body#p
        else
          CoqNotation.definition (name#p) (generics#p) (List.map ~f:(fun x -> x#p) params) typ body#p
      (* TODO: Why is type not available here ? *)

      method item'_HaxError ~super:_ _x2 = default_document_for "item'_HaxError"

      method item'_IMacroInvokation ~super:_ ~macro:_ ~argument:_ ~span:_
          ~witness:_ =
        default_document_for "item'_IMacroInvokation"


      method item'_Impl ~super:_ ~generics ~self_ty ~of_trait ~items
          ~parent_bounds:_ ~safety:_ =
        let (name_document,_) = of_trait#v in
        CoqNotation.instance
          (self_ty#p ^^ string "_" ^^ name_document#p)
          (generics#p)
          []
          (name_document#p)
          (braces (nest 2 (concat_map (fun x -> break 1 ^^ name_document#p ^^ !^"_" ^^ x#p) items) ^^ break 1))

      method item'_NotImplementedYet = string "(* NotImplementedYet *)"

      method item'_Quote ~super:_ ~quote:_ ~origin:_ =
        default_document_for "item'_Quote"

      method item'_Trait ~super:_ ~name ~generics ~items ~safety:_ =
        CoqNotation.class_
          (name#p)
          (generics#p)
          []
          (!^"Type")
          (braces (nest 2 (concat_map (fun x -> break 1 ^^ (name#p ^^ !^"_" (* TODO: this information should be given to [trait_item] instead *)) ^^ x#p) items) ^^ break 1))
        ^^ break 1
        ^^ !^"Arguments" ^^ space ^^ name#p ^^ colon ^^ !^"clear implicits" ^^ dot

        ^^ !^"Arguments" ^^ space ^^ name#p ^^ space ^^ !^"(_)" ^^ dot

      method item'_TyAlias ~super:_ ~name ~generics:_ ~ty =
        string "Notation" ^^ space ^^ string "\"'" ^^ name#p ^^ string "'\"" ^^ space ^^ string ":=" ^^ space ^^ ty#p ^^ dot

      method item'_Type_struct ~super:_ ~name ~generics ~tuple_struct:_ ~arguments =
        CoqNotation.record (name#p) (generics#p) [] (string "Type") (braces ( nest 2 (concat_map (fun (ident, typ, attr) -> break 1 ^^ name#p ^^ !^"_" ^^ ident#p ^^ space ^^ colon ^^ space ^^ typ#p) arguments) ^^ break 1 ))

      method item'_Type_enum ~super:_ ~name ~generics ~variants =
        CoqNotation.inductive (name#p) (generics#p) [] (string "Type") (separate_map (break 1) (fun x -> string "|" ^^ space ^^ x#p) variants)

      method item'_Type ~super:_ ~name:_ ~generics:_ ~variants:_ ~is_struct:_ =
        default_document_for "item'_Type"

      method item'_Use ~super:_ ~path ~is_external:_ ~rename:_ =
        let path_string = (
          match List.rev path with
          | [a] -> a
          | (a :: l) -> String.concat ~sep:"_" (List.map ~f:String.capitalize (List.rev l)) ^ "." ^ a
          | _ -> ""
        ) in
        string "Require Import" ^^ space ^^ string path_string ^^ dot
        ^^ break 1 ^^ string "Export" ^^ space ^^ string path_string ^^ dot

      method lhs_LhsArbitraryExpr ~e:_ ~witness:_ =
        default_document_for "lhs_LhsArbitraryExpr"

      method lhs_LhsArrayAccessor ~e:_ ~typ:_ ~index:_ ~witness:_ =
        default_document_for "lhs_LhsArrayAccessor"

      method lhs_LhsFieldAccessor_field ~e:_ ~typ:_ ~field:_ ~witness:_ =
        default_document_for "lhs_LhsFieldAccessor_field"

      method lhs_LhsFieldAccessor_tuple ~e:_ ~typ:_ ~nth:_ ~size:_ ~witness:_ =
        default_document_for "lhs_LhsFieldAccessor_tuple"

      method lhs_LhsLocalVar ~var:_ ~typ:_ =
        default_document_for "lhs_LhsLocalVar"

      method literal_Bool x1 = string (if x1 then "true" else "false")
      method literal_Char _x1 = default_document_for "literal_Char"

      method literal_Float ~value:_ ~negative:_ ~kind:_ =
        default_document_for "literal_Float"

      method literal_Int ~value ~negative:_ ~kind:_ =
        string value

      method literal_String x1 = string "\"" ^^ string x1 ^^ string "\"%string"

      method loop_kind_ForIndexLoop ~start:_ ~end_:_ ~var:_ ~var_typ:_
          ~witness:_ =
        default_document_for "loop_kind_ForIndexLoop"

      method loop_kind_ForLoop ~pat:_ ~it:_ ~witness:_ =
        default_document_for "loop_kind_ForLoop"

      method loop_kind_UnconditionalLoop =
        default_document_for "loop_kind_UnconditionalLoop"

      method loop_kind_WhileLoop ~condition:_ ~witness:_ =
        default_document_for "loop_kind_WhileLoop"

      method loop_state ~init:_ ~bpat:_ ~witness:_ =
        default_document_for "loop_state"

      method modul _x1 = default_document_for "modul"

      method param ~pat ~typ ~typ_span:_ ~attrs:_ =
        parens (pat#p ^^ space ^^ colon ^^ space ^^ typ#p)

      method pat ~p ~span:_ ~typ:_ = p#p

      method pat'_PAscription ~super:_ ~typ ~typ_span:_ ~pat =
        pat#p ^^ space ^^ colon ^^ space ^^ typ#p

      method pat'_PBinding ~super:_ ~mut:_ ~mode:_ ~var ~typ:_ ~subpat:_ =
        var#p (* ^^ space ^^ colon ^^ space ^^ typ#p *)

      method pat'_PConstant ~super:_ ~lit =
        lit#p

      method pat'_PConstruct_inductive ~super:_ ~constructor ~is_record:_
          ~is_struct:_ ~fields =
        constructor#p ^^ concat_map (fun (ident, exp) -> space ^^ exp#p) fields

      method pat'_PConstruct_tuple ~super:_ ~components =
        parens ( separate_map comma (fun x -> x#p) components )

      method pat'_PDeref ~super:_ ~subpat:_ ~witness:_ =
        default_document_for "pat'_PDeref"

      method pat'_PWild = string "_"
      method printer_name = default_string_for "printer_name"

      method projection_predicate ~impl:_ ~assoc_item:_ ~typ:_ =
        default_document_for "projection_predicate"

      method safety_kind_Safe = default_document_for "safety_kind_Safe"
      method safety_kind_Unsafe _x1 = default_document_for "safety_kind_Unsafe"

      method supported_monads_MException _x1 =
        default_document_for "supported_monads_MException"

      method supported_monads_MOption =
        default_document_for "supported_monads_MOption"

      method supported_monads_MResult _x1 =
        default_document_for "supported_monads_MResult"

      method trait_goal ~trait ~args:_ =
        trait#p (* ^^ concat_map (fun x -> space ^^ x#p) args *)

      method trait_item ~ti_span:_ ~ti_generics:_ ~ti_v ~ti_ident
          ~ti_attrs:_ =
        ti_ident#p ^^ space ^^ colon ^^ space ^^ ti_v#p ^^ semi

      method trait_item'_TIDefault ~params:_ ~body:_ ~witness:_ =
        default_document_for "trait_item'_TIDefault"

      method trait_item'_TIFn x1 = x1#p
      method trait_item'_TIType x1 =
        string "Type" (* TODO, type should implement x1 traits *)
        (* concat_map (fun x -> x#p) x1 *)

      method ty_TApp_application ~typ ~generics =
        typ#p ^^ concat_map (fun x -> space ^^ parens(x#p)) generics

      method ty_TApp_tuple ~types = parens( separate_map star (fun x -> (new printer)#entrypoint_ty x) types )
      method ty_TArray ~typ:_ ~length:_ = default_document_for "ty_TArray"
      method ty_TArrow x1 x2 = concat_map (fun x -> x#p ^^ space ^^ string "->" ^^ space) x1 ^^ x2#p

      method ty_TAssociatedType ~impl ~item =
        impl#p ^^ string "_" ^^ item#p

      method ty_TBool = string "bool"
      method ty_TChar = default_document_for "ty_TChar"
      method ty_TDyn ~witness:_ ~goals:_ = default_document_for "ty_TDyn"
      method ty_TFloat _x1 = default_document_for "ty_TFloat"
      method ty_TInt x1 =
        match x1 with
        | { size; signedness } ->
          match size with
          | S8 -> string "t_u8"
          | S16 -> string "t_u16"
          | S32 -> string "t_u32"
          | S64 -> string "t_u64"
          | S128 -> string "t_u128"
          | SSize -> string "t_usize"

      method ty_TOpaque _x1 = default_document_for "ty_TOpaque"
      method ty_TParam x1 = x1#p
      method ty_TRawPointer ~witness:_ = default_document_for "ty_TRawPointer"

      method ty_TRef ~witness:_ ~region:_ ~typ:_ ~mut:_ =
        default_document_for "ty_TRef"

      method ty_TSlice ~witness:_ ~ty = !^"t_Slice" ^^ space ^^ ty#p
      method ty_TStr = string "string"

      method item'_Enum_Variant ~name ~arguments ~is_record ~attrs:_ =
        if is_record
        then
          concat_map (fun (ident,typ,attr) -> ident#p ^^ space ^^ colon ^^ space ^^ typ#p) arguments ^^ semi
        else
          if List.length arguments == 0
          then name#p
          else
            name#p
            ^^ space ^^ colon ^^ space
            ^^ separate_map (space ^^ string "->" ^^ space) (fun (ident,typ,attr) -> typ#p (* parens (ident#p ^^ space ^^ colon ^^ space ^^ typ#p) *)) arguments ^^ space ^^ string "->" ^^ space ^^ string "_"
      (* END GENERATED *)

      method module_path_separator = "."
      method concrete_ident ~local:_ id : document =
        string id.definition
      val mutable current_namespace : (string * string list) option = None
    end
end

module MyPrinter = Make (InputLanguage) (struct let default x = x end)
let translate _ _ ~bundles:_ (items : AST.item list) :
  Types.file list =
  let my_printer = new MyPrinter.printer in

  (* let _ = Gen.map (fun apply -> *)
  (*     let printer = new MyPrinter.printer in *)
  (*     let doc = apply printer in *)
  (*     let buf = Buffer.create 0 in *)
  (*     PPrint.ToBuffer.pretty 1.0 80 buf doc; *)
  (*     (Buffer.contents buf (\* , printer#get_span_data () *\))) in *)

  U.group_items_by_namespace items
  |> Map.to_alist
  |> List.map ~f:(fun (ns, items) ->
         let mod_name =
           String.concat ~sep:"_"
             (List.map
                ~f:(map_first_letter String.uppercase)
                (fst ns :: snd ns))
         in

         Types.
           {
             path = mod_name ^ ".v";
             contents =
               hardcoded_coq_headers ^ "\n" ^
               String.concat ~sep:"\n" (
                 List.map
                   ~f:(fun item ->
                       let buf = Buffer.create 0 in
                       PPrint.ToBuffer.pretty 1.0 80 buf (my_printer#entrypoint_item item);
                       Buffer.contents buf
                     )
                   items);
             sourcemap = None;
           })

open Phase_utils

module TransformToInputLanguage =
  [%functor_application
  Phases.Reject.Unsafe(Features.Rust)
  |> Phases.Reject.RawOrMutPointer
  |> Phases.And_mut_defsite
  |> Phases.Reconstruct_asserts
  |> Phases.Reconstruct_for_loops
  |> Phases.Direct_and_mut
  |> Phases.Reject.Arbitrary_lhs
  |> Phases.Drop_blocks
  |> Phases.Drop_match_guards
  |> Phases.Reject.Continue
  |> Phases.Drop_references
  |> Phases.Trivialize_assign_lhs
  |> Phases.Reconstruct_question_marks
  |> Side_effect_utils.Hoist
  |> Phases.Local_mutation
  |> Phases.Reject.Continue
  |> Phases.Cf_into_monads
  |> Phases.Reject.EarlyExit
  |> Phases.Functionalize_loops
  |> Phases.Reject.As_pattern
  |> Phases.Reject.Dyn
  |> Phases.Reject.Trait_item_default
  |> SubtypeToInputLanguage
  |> Identity
  ]
  [@ocamlformat "disable"]

let apply_phases (_bo : BackendOptions.t) (items : Ast.Rust.item list) :
    AST.item list =
  TransformToInputLanguage.ditems items

