(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import String.

From Core Require Import Core_Marker.
Export Core_Marker.

Definition t_Never : Type := False.

Definition never_to_any `{v_T : Type} `{t_Sized v_T} (x : t_Never) : v_T :=
  (match x with end).

Fixpoint panic (expr : string) `{false = true} : t_Never :=
  never_to_any (Bool.diff_false_true H).

Definition panic_explicit (_ : unit) `{false = true} : t_Never :=
  never_to_any (Bool.diff_false_true H).
