(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import String.

From Core Require Import Core_Base_Int.
Export Core_Base_Int.

From Core Require Import Core_Primitive.
Export Core_Primitive.

From Core Require Import Core_Cmp.
Export Core_Cmp.

From Core Require Import Core_Convert.
Export Core_Convert.

(* NotImplementedYet *)

Instance t_From_62544291 : t_From (t_HaxInt) (t_u8) :=
  {
    t_From_f_from := fun (x : t_u8) => t_U8_f_v (t_u8_0 x);
  }.

Instance t_From_1006987144 : t_From (t_u8) (t_HaxInt) :=
  {
    t_From_f_from := fun (x : t_HaxInt) => Build_t_u8 (Build_t_U8 x)
  }.

Instance t_From_1039663005 : t_From (t_HaxInt) (t_u16) :=
  {
    t_From_f_from := fun (x : t_u16) => t_U16_f_v (t_u16_0 x);
  }.

Instance t_From_1052282100 : t_From (t_u16) (t_HaxInt) :=
  {
    t_From_f_from := fun (x : t_HaxInt) => Build_t_u16 (Build_t_U16 x);
  }.

Instance t_From_529475850 : t_From (t_HaxInt) (t_u32) :=
  {
    t_From_f_from := fun (x : t_u32) => t_U32_f_v (t_u32_0 x);
  }.

Instance t_From_447931916 : t_From (t_u32) (t_HaxInt) :=
  {
    t_From_f_from := fun (x : t_HaxInt) => Build_t_u32 (Build_t_U32 x);
  }.

Instance t_From_616445870 : t_From (t_HaxInt) (t_u64) :=
  {
    t_From_f_from := fun (x : t_u64) => t_U64_f_v (t_u64_0 x);
  }.

Instance t_From_70650389 : t_From (t_u64) (t_HaxInt) :=
  {
    t_From_f_from := fun (x : t_HaxInt) => Build_t_u64 (Build_t_U64 x);
  }.

Instance t_From_184355489 : t_From (t_HaxInt) (t_u128) :=
  {
    t_From_f_from := fun (x : t_u128) => t_U128_f_v (t_u128_0 x);
  }.

Instance t_From_844812452 : t_From (t_u128) (t_HaxInt) :=
  {
    t_From_f_from := fun (x : t_HaxInt) => Build_t_u128 (Build_t_U128 x);
  }.

Instance t_From_946823391 : t_From (t_HaxInt) (t_usize) :=
  {
    t_From_f_from := fun (x : t_usize) => t_U64_f_v (t_usize_0 x);
  }.

Instance t_From_655514338 : t_From (t_usize) (t_HaxInt) :=
  {
    t_From_f_from := fun (x : t_HaxInt) => Build_t_usize (Build_t_U64 x);
  }.
