(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import String.
From Core Require Import Core_Marker.

From Core Require Import Core_Clone.
Export Core_Clone.

From Core Require Import Core_Int.
Export Core_Int.

Definition t_u128 : Type :=
  t_U128.

Instance t_u128_t_Clone : t_Clone (t_u128) :=
  {
    t_Clone_f_clone := fun (self : t_u128) =>
       (t_Clone_f_clone ( self));
  }.

Instance t_u128_t_PartialEq : t_PartialEq (t_u128) (t_u128) :=
  {
    t_PartialEq_f_eq := fun (self : t_u128) (rhs : t_u128) =>
      t_PartialEq_f_eq (self) (rhs);
    t_PartialEq_f_ne := fun (self : t_u128) (rhs : t_u128) =>
      negb (t_PartialEq_f_eq (self) (rhs));
  }.

Instance t_u128_t_PartialOrd : t_PartialOrd (t_u128) (t_u128) :=
  {
    t_PartialOrd_f_partial_cmp := fun (self : t_u128) (rhs : t_u128) =>
      t_PartialOrd_f_partial_cmp (self) (rhs);
    t_PartialOrd_f_lt := fun (self : t_u128) (rhs : t_u128) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Less) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_le := fun (self : t_u128) (rhs : t_u128) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Less
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_gt := fun (self : t_u128) (rhs : t_u128) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Greater) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_ge := fun (self : t_u128) (rhs : t_u128) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Greater
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
  }.

Definition t_u16 : Type :=
  t_U16.

Instance t_u16_t_Clone : t_Clone (t_u16) :=
  {
    t_Clone_f_clone := fun (self : t_u16) =>
       (t_Clone_f_clone (self));
  }.

Instance t_u16_t_PartialEq : t_PartialEq (t_u16) (t_u16) :=
  {
    t_PartialEq_f_eq := fun (self : t_u16) (rhs : t_u16) =>
      t_PartialEq_f_eq (self) (rhs);
    t_PartialEq_f_ne := fun (self : t_u16) (rhs : t_u16) =>
      negb (t_PartialEq_f_eq (self) (rhs));
  }.

Instance t_u16_t_PartialOrd : t_PartialOrd (t_u16) (t_u16) :=
  {
    t_PartialOrd_f_partial_cmp := fun (self : t_u16) (rhs : t_u16) =>
      t_PartialOrd_f_partial_cmp (self) (rhs);
    t_PartialOrd_f_lt := fun (self : t_u16) (rhs : t_u16) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Less) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_le := fun (self : t_u16) (rhs : t_u16) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Less
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_gt := fun (self : t_u16) (rhs : t_u16) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Greater) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_ge := fun (self : t_u16) (rhs : t_u16) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Greater
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
  }.

Definition t_u32 : Type :=
  t_U32.

Instance t_u32_t_Clone : t_Clone (t_u32) :=
  {
    t_Clone_f_clone := fun (self : t_u32) =>
       (t_Clone_f_clone (self));
  }.

Instance t_u32_t_PartialEq : t_PartialEq (t_u32) (t_u32) :=
  {
    t_PartialEq_f_eq := fun (self : t_u32) (rhs : t_u32) =>
      t_PartialEq_f_eq (self) (rhs);
    t_PartialEq_f_ne := fun (self : t_u32) (rhs : t_u32) =>
      negb (t_PartialEq_f_eq (self) (rhs));
  }.

Instance t_u32_t_PartialOrd : t_PartialOrd (t_u32) (t_u32) :=
  {
    t_PartialOrd_f_partial_cmp := fun (self : t_u32) (rhs : t_u32) =>
      t_PartialOrd_f_partial_cmp (self) (rhs);
    t_PartialOrd_f_lt := fun (self : t_u32) (rhs : t_u32) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Less) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_le := fun (self : t_u32) (rhs : t_u32) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Less
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_gt := fun (self : t_u32) (rhs : t_u32) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Greater) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_ge := fun (self : t_u32) (rhs : t_u32) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Greater
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
  }.

Definition t_u64 : Type :=
  t_U64.

Instance t_u64_t_Clone : t_Clone (t_u64) :=
  {
    t_Clone_f_clone := fun (self : t_u64) =>
       (t_Clone_f_clone (self));
  }.

Instance t_u64_t_PartialEq : t_PartialEq (t_u64) (t_u64) :=
  {
    t_PartialEq_f_eq := fun (self : t_u64) (rhs : t_u64) =>
      t_PartialEq_f_eq (self) (rhs);
    t_PartialEq_f_ne := fun (self : t_u64) (rhs : t_u64) =>
      negb (t_PartialEq_f_eq (self) (rhs));
  }.

Instance t_u64_t_PartialOrd : t_PartialOrd (t_u64) (t_u64) :=
  {
    t_PartialOrd_f_partial_cmp := fun (self : t_u64) (rhs : t_u64) =>
      t_PartialOrd_f_partial_cmp (self) (rhs);
    t_PartialOrd_f_lt := fun (self : t_u64) (rhs : t_u64) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Less) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_le := fun (self : t_u64) (rhs : t_u64) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Less
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_gt := fun (self : t_u64) (rhs : t_u64) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Greater) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_ge := fun (self : t_u64) (rhs : t_u64) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Greater
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
  }.

Definition t_u8 : Type :=
  t_U8.

Instance t_u8_t_Clone : t_Clone (t_u8) :=
  {
    t_Clone_f_clone := fun (self : t_u8) =>
       (t_Clone_f_clone (self));
  }.

Instance t_u8_t_PartialEq : t_PartialEq (t_u8) (t_u8) :=
  {
    t_PartialEq_f_eq := fun (self : t_u8) (rhs : t_u8) =>
      t_PartialEq_f_eq (self) (rhs);
    t_PartialEq_f_ne := fun (self : t_u8) (rhs : t_u8) =>
      negb (t_PartialEq_f_eq (self) (rhs));
  }.

Instance t_u8_t_PartialOrd : t_PartialOrd (t_u8) (t_u8) :=
  {
    t_PartialOrd_f_partial_cmp := fun (self : t_u8) (rhs : t_u8) =>
      t_PartialOrd_f_partial_cmp (self) (rhs);
    t_PartialOrd_f_lt := fun (self : t_u8) (rhs : t_u8) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Less) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_le := fun (self : t_u8) (rhs : t_u8) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Less
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_gt := fun (self : t_u8) (rhs : t_u8) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Greater) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_ge := fun (self : t_u8) (rhs : t_u8) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Greater
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
  }.

Definition t_usize : Type :=
  t_U64.

Instance t_usize_t_Clone : t_Clone (t_usize) :=
  {
    t_Clone_f_clone := fun (self : t_usize) =>
       (t_Clone_f_clone (self));
  }.

Instance t_usize_t_PartialEq : t_PartialEq (t_usize) (t_usize) :=
  {
    t_PartialEq_f_eq := fun (self : t_usize) (rhs : t_usize) =>
      t_PartialEq_f_eq (self) (rhs);
    t_PartialEq_f_ne := fun (self : t_usize) (rhs : t_usize) =>
      negb (t_PartialEq_f_eq (self) (rhs));
  }.

Instance t_usize_t_PartialOrd : t_PartialOrd (t_usize) (t_usize) :=
  {
    t_PartialOrd_f_partial_cmp := fun (self : t_usize) (rhs : t_usize) =>
      t_PartialOrd_f_partial_cmp (self) (rhs);
    t_PartialOrd_f_lt := fun (self : t_usize) (rhs : t_usize) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Less) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_le := fun (self : t_usize) (rhs : t_usize) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Less
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_gt := fun (self : t_usize) (rhs : t_usize) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Greater) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_ge := fun (self : t_usize) (rhs : t_usize) =>
      match t_PartialOrd_f_partial_cmp (self) (rhs) with
      |  Option_Some (Ordering_Greater
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
  }.

Instance t_u8_t_Mul : t_Mul (t_u8) (t_u8) :=
  {
    t_Mul_f_Output := t_u8;
    t_Mul_f_mul := fun (self : t_u8) (rhs : t_u8) =>
       (t_Mul_f_mul (self) (rhs));
  }.

Instance t_u8_t_Rem : t_Rem (t_u8) (t_u8) :=
  {
    t_Rem_f_Output := t_u8;
    t_Rem_f_rem := fun (self : t_u8) (rhs : t_u8) =>
       (t_Rem_f_rem (self) (rhs));
  }.

Instance t_u8_t_Add : t_Add (t_u8) (t_u8) :=
  {
    t_Add_f_Output := t_u8;
    t_Add_f_add := fun (self : t_u8) (rhs : t_u8) =>
       (t_Add_f_add (self) (rhs));
  }.

Instance t_u8_t_Div : t_Div (t_u8) (t_u8) :=
  {
    t_Div_f_Output := t_u8;
    t_Div_f_div := fun (self : t_u8) (rhs : t_u8) =>
       (t_Div_f_div (self) (rhs));
  }.

Instance t_u16_t_Mul : t_Mul (t_u16) (t_u16) :=
  {
    t_Mul_f_Output := t_u16;
    t_Mul_f_mul := fun (self : t_u16) (rhs : t_u16) =>
       (t_Mul_f_mul (self) (rhs));
  }.

Instance t_u16_t_Rem : t_Rem (t_u16) (t_u16) :=
  {
    t_Rem_f_Output := t_u16;
    t_Rem_f_rem := fun (self : t_u16) (rhs : t_u16) =>
       (t_Rem_f_rem (self) (rhs));
  }.

Instance t_u16_t_Add : t_Add (t_u16) (t_u16) :=
  {
    t_Add_f_Output := t_u16;
    t_Add_f_add := fun (self : t_u16) (rhs : t_u16) =>
       (t_Add_f_add (self) (rhs));
  }.

Instance t_u16_t_Div : t_Div (t_u16) (t_u16) :=
  {
    t_Div_f_Output := t_u16;
    t_Div_f_div := fun (self : t_u16) (rhs : t_u16) =>
       (t_Div_f_div (self) (rhs));
  }.

Instance t_u32_t_Mul : t_Mul (t_u32) (t_u32) :=
  {
    t_Mul_f_Output := t_u32;
    t_Mul_f_mul := fun (self : t_u32) (rhs : t_u32) =>
       (t_Mul_f_mul (self) (rhs));
  }.

Instance t_u32_t_Rem : t_Rem (t_u32) (t_u32) :=
  {
    t_Rem_f_Output := t_u32;
    t_Rem_f_rem := fun (self : t_u32) (rhs : t_u32) =>
       (t_Rem_f_rem (self) (rhs));
  }.

Instance t_u32_t_Add : t_Add (t_u32) (t_u32) :=
  {
    t_Add_f_Output := t_u32;
    t_Add_f_add := fun (self : t_u32) (rhs : t_u32) =>
       (t_Add_f_add (self) (rhs));
  }.

Instance t_u32_t_Div : t_Div (t_u32) (t_u32) :=
  {
    t_Div_f_Output := t_u32;
    t_Div_f_div := fun (self : t_u32) (rhs : t_u32) =>
       (t_Div_f_div (self) (rhs));
  }.

Instance t_u64_t_Mul : t_Mul (t_u64) (t_u64) :=
  {
    t_Mul_f_Output := t_u64;
    t_Mul_f_mul := fun (self : t_u64) (rhs : t_u64) =>
       (t_Mul_f_mul (self) (rhs));
  }.

Instance t_u64_t_Rem : t_Rem (t_u64) (t_u64) :=
  {
    t_Rem_f_Output := t_u64;
    t_Rem_f_rem := fun (self : t_u64) (rhs : t_u64) =>
       (t_Rem_f_rem (self) (rhs));
  }.

Instance t_u64_t_Add : t_Add (t_u64) (t_u64) :=
  {
    t_Add_f_Output := t_u64;
    t_Add_f_add := fun (self : t_u64) (rhs : t_u64) =>
       (t_Add_f_add (self) (rhs));
  }.

Instance t_u64_t_Div : t_Div (t_u64) (t_u64) :=
  {
    t_Div_f_Output := t_u64;
    t_Div_f_div := fun (self : t_u64) (rhs : t_u64) =>
       (t_Div_f_div (self) (rhs));
  }.

Instance t_u128_t_Mul : t_Mul (t_u128) (t_u128) :=
  {
    t_Mul_f_Output := t_u128;
    t_Mul_f_mul := fun (self : t_u128) (rhs : t_u128) =>
       (t_Mul_f_mul (self) (rhs));
  }.

Instance t_u128_t_Rem : t_Rem (t_u128) (t_u128) :=
  {
    t_Rem_f_Output := t_u128;
    t_Rem_f_rem := fun (self : t_u128) (rhs : t_u128) =>
       (t_Rem_f_rem (self) (rhs));
  }.

Instance t_u128_t_Add : t_Add (t_u128) (t_u128) :=
  {
    t_Add_f_Output := t_u128;
    t_Add_f_add := fun (self : t_u128) (rhs : t_u128) =>
       (t_Add_f_add (self) (rhs));
  }.

Instance t_u128_t_Div : t_Div (t_u128) (t_u128) :=
  {
    t_Div_f_Output := t_u128;
    t_Div_f_div := fun (self : t_u128) (rhs : t_u128) =>
       (t_Div_f_div (self) (rhs));
  }.

Instance t_usize_t_Mul : t_Mul (t_usize) (t_usize) :=
  {
    t_Mul_f_Output := t_usize;
    t_Mul_f_mul := fun (self : t_usize) (rhs : t_usize) =>
       (t_Mul_f_mul (self) (rhs));
  }.

Instance t_usize_t_Rem : t_Rem (t_usize) (t_usize) :=
  {
    t_Rem_f_Output := t_usize;
    t_Rem_f_rem := fun (self : t_usize) (rhs : t_usize) =>
       (t_Rem_f_rem (self) (rhs));
  }.

Instance t_usize_t_Add : t_Add (t_usize) (t_usize) :=
  {
    t_Add_f_Output := t_usize;
    t_Add_f_add := fun (self : t_usize) (rhs : t_usize) =>
       (t_Add_f_add (self) (rhs));
  }.

Instance t_usize_t_Div : t_Div (t_usize) (t_usize) :=
  {
    t_Div_f_Output := t_usize;
    t_Div_f_div := fun (self : t_usize) (rhs : t_usize) =>
       (t_Div_f_div (self) (rhs));
  }.
