(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import String.
From Core Require Import Core_Marker.

Definition t_Seq `{v_T : Type} `{t_Sized v_T} : Type := list v_T.
Arguments t_Seq:clear implicits.
Arguments t_Seq (_) {_}.

Notation "'t_LIST'" := list.
Notation "'LIST_NIL'" := nil.
Notation "'LIST_CONS'" := cons.
