(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import String.
From Core Require Import Core_Marker.

Class t_From `{v_Self : Type} `{v_T : Type} `{t_Sized v_Self} `{t_Sized v_T} : Type :=
  {
    t_From_f_from : v_T -> v_Self;
  }.
Arguments t_From:clear implicits.
Arguments t_From (_) (_) {_} {_}.

Instance v_T_t_From `{v_T : Type} `{t_Sized v_T} : t_From (v_T) (v_T) :=
  {
    t_From_f_from := fun (t : v_T) =>
      t;
  }.

Class t_Into `{v_Self : Type} `{v_T : Type} `{t_Sized v_Self} `{t_Sized v_T} : Type :=
  {
    t_Into_f_into : v_Self -> v_T;
  }.
Arguments t_Into:clear implicits.
Arguments t_Into (_) (_) {_} {_}.

Instance v_T_t_Into `{v_T : Type} `{v_U : Type} `{t_Sized v_T} `{t_Sized v_U} `{t_From v_U v_T} : t_Into (v_T) (v_U) :=
  {
    t_Into_f_into := fun (self : v_T) =>
      t_From_f_from (self);
  }.
