(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import String.
From Core Require Import Core_Marker.

From Core Require Import Core_Base_Int_Base_impl.
Export Core_Base_Int_Base_impl.

From Core Require Import Core_Coerce.
Export Core_Coerce.

From Core Require Import Core_Convert.
Export Core_Convert.

From Core Require Import Core_Ops_Bit.
Export Core_Ops_Bit.

From Core Require Import Core_Ops_Arith.
Export Core_Ops_Arith.

Class t_Constants `{v_Self : Type} : Type :=
  {
    t_Constants_f_ZERO : v_Self;
    t_Constants_f_ONE : v_Self;
    t_Constants_f_MIN : v_Self;
    t_Constants_f_MAX : v_Self;
  }.
Arguments t_Constants:clear implicits.
Arguments t_Constants (_).

Definition impl_21__WORDSIZE : t_HaxInt :=
  v_WORDSIZE_8_.

Definition impl_48__WORDSIZE : t_HaxInt :=
  v_WORDSIZE_16_.

Definition impl_75__WORDSIZE : t_HaxInt :=
  v_WORDSIZE_32_.

Definition impl_102__WORDSIZE : t_HaxInt :=
  v_WORDSIZE_64_.

Definition impl_129__WORDSIZE : t_HaxInt :=
  v_WORDSIZE_128_.

Record t_U128 : Type :=
  {
    t_U128_f_v : t_HaxInt
  }.

Instance t_U128_t_Constants : t_Constants (t_U128) :=
  {
    t_Constants_f_ZERO := Build_t_U128 (impl_9__ZERO);
    t_Constants_f_ONE := Build_t_U128 (impl_9__ONE);
    t_Constants_f_MIN := Build_t_U128 (impl_9__ZERO);
    t_Constants_f_MAX := Build_t_U128 (v_WORDSIZE_128_SUB_1_);
  }.

Instance t_U128_t_Clone : t_Clone (t_U128) :=
  {
    t_Clone_f_clone := fun (self : t_U128) =>
      Build_t_U128 (t_Clone_f_clone (t_U128_f_v self));
  }.

Record t_U16 : Type :=
  {
    t_U16_f_v : t_HaxInt
  }.

Instance t_U16_t_Constants : t_Constants (t_U16) :=
  {
    t_Constants_f_ZERO := Build_t_U16 (impl_9__ZERO);
    t_Constants_f_ONE := Build_t_U16 (impl_9__ONE);
    t_Constants_f_MIN := Build_t_U16 (impl_9__ZERO);
    t_Constants_f_MAX := Build_t_U16 (v_WORDSIZE_16_SUB_1_);
  }.

Instance t_U16_t_Clone : t_Clone (t_U16) :=
  {
    t_Clone_f_clone := fun (self : t_U16) =>
      Build_t_U16 (t_Clone_f_clone (t_U16_f_v self));
  }.

Record t_U32 : Type :=
  {
    t_U32_f_v : t_HaxInt
  }.

Definition impl_21__BITS : t_U32 :=
  Build_t_U32 (v_BITS_8_).

Definition impl_48__BITS : t_U32 :=
  Build_t_U32 (v_BITS_16_).

Instance t_U32_t_Constants : t_Constants (t_U32) :=
  {
    t_Constants_f_ZERO := Build_t_U32 (impl_9__ZERO);
    t_Constants_f_ONE := Build_t_U32 (impl_9__ONE);
    t_Constants_f_MIN := Build_t_U32 (impl_9__ZERO);
    t_Constants_f_MAX := Build_t_U32 (v_WORDSIZE_32_SUB_1_);
  }.

Definition impl_75__BITS : t_U32 :=
  Build_t_U32 (v_BITS_32_).

Instance t_U32_t_Clone : t_Clone (t_U32) :=
  {
    t_Clone_f_clone := fun (self : t_U32) =>
      Build_t_U32 (t_Clone_f_clone (t_U32_f_v self));
  }.

Definition impl_102__BITS : t_U32 :=
  Build_t_U32 (v_BITS_64_).

Definition impl_129__BITS : t_U32 :=
  Build_t_U32 (v_BITS_128_).

Record t_U64 : Type :=
  {
    t_U64_f_v : t_HaxInt
  }.

Instance t_U64_t_Constants : t_Constants (t_U64) :=
  {
    t_Constants_f_ZERO := Build_t_U64 (impl_9__ZERO);
    t_Constants_f_ONE := Build_t_U64 (impl_9__ONE);
    t_Constants_f_MIN := Build_t_U64 (impl_9__ZERO);
    t_Constants_f_MAX := Build_t_U64 (v_WORDSIZE_64_SUB_1_);
  }.

Instance t_U64_t_Clone : t_Clone (t_U64) :=
  {
    t_Clone_f_clone := fun (self : t_U64) =>
      Build_t_U64 (t_Clone_f_clone (t_U64_f_v self));
  }.

Record t_U8 : Type :=
  {
    t_U8_f_v : t_HaxInt
  }.

Instance t_U8_t_Constants : t_Constants (t_U8) :=
  {
    t_Constants_f_ZERO := Build_t_U8 (impl_9__ZERO);
    t_Constants_f_ONE := Build_t_U8 (impl_9__ONE);
    t_Constants_f_MIN := Build_t_U8 (impl_9__ZERO);
    t_Constants_f_MAX := Build_t_U8 (v_WORDSIZE_8_SUB_1_);
  }.

Instance t_U8_t_Clone : t_Clone (t_U8) :=
  {
    t_Clone_f_clone := fun (self : t_U8) =>
      Build_t_U8 (t_Clone_f_clone (t_U8_f_v self));
  }.

Instance t_U8_t_Abstraction : t_Abstraction (t_U8) :=
  {
    t_Abstraction_f_AbstractType := t_HaxInt;
    t_Abstraction_f_lift := fun (self : t_U8) =>
      t_U8_f_v self;
  }.

Instance t_U8_t_PartialEq : t_PartialEq (t_U8) (t_U8) :=
  {
    t_PartialEq_f_eq := fun (self : t_U8) (rhs : t_U8) =>
      t_PartialEq_f_eq (t_Abstraction_f_lift (t_Clone_f_clone (self)) : t_HaxInt) (t_Abstraction_f_lift (t_Clone_f_clone (rhs)) : t_HaxInt);
    t_PartialEq_f_ne := fun (self : t_U8) (rhs : t_U8) =>
      negb (t_PartialEq_f_eq (t_Abstraction_f_lift (t_Clone_f_clone (self)) : t_HaxInt) (t_Abstraction_f_lift (t_Clone_f_clone (rhs)) : t_HaxInt));
  }.

Instance t_U8_t_PartialOrd : t_PartialOrd (t_U8) (t_U8) :=
  {
    t_PartialOrd_f_partial_cmp := fun (self : t_U8) (rhs : t_U8) =>
      t_PartialOrd_f_partial_cmp (t_Abstraction_f_lift (t_Clone_f_clone (self)) : t_HaxInt) (t_Abstraction_f_lift (t_Clone_f_clone (rhs)) : t_HaxInt);
    t_PartialOrd_f_lt := fun (self : t_U8) (rhs : t_U8) =>
      match t_PartialOrd_f_partial_cmp (t_Abstraction_f_lift (t_Clone_f_clone (self)) : t_HaxInt) (t_Abstraction_f_lift (t_Clone_f_clone (rhs)) : t_HaxInt) with
      |  Option_Some (Ordering_Less) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_le := fun (self : t_U8) (rhs : t_U8) =>
      match t_PartialOrd_f_partial_cmp (t_Abstraction_f_lift (t_Clone_f_clone (self)) : t_HaxInt) (t_Abstraction_f_lift (t_Clone_f_clone (rhs)) : t_HaxInt) with
      |  Option_Some (Ordering_Less
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_gt := fun (self : t_U8) (rhs : t_U8) =>
      match t_PartialOrd_f_partial_cmp (t_Abstraction_f_lift (t_Clone_f_clone (self)) : t_HaxInt) (t_Abstraction_f_lift (t_Clone_f_clone (rhs)) : t_HaxInt) with
      |  Option_Some (Ordering_Greater) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_ge := fun (self : t_U8) (rhs : t_U8) =>
      match t_PartialOrd_f_partial_cmp (t_Abstraction_f_lift (t_Clone_f_clone (self)) : t_HaxInt) (t_Abstraction_f_lift (t_Clone_f_clone (rhs)) : t_HaxInt) with
      |  Option_Some (Ordering_Greater
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
  }.

Instance t_U16_t_Abstraction : t_Abstraction (t_U16) :=
  {
    t_Abstraction_f_AbstractType := t_HaxInt;
    t_Abstraction_f_lift := fun (self : t_U16) =>
      t_U16_f_v self;
  }.

Instance t_U16_t_PartialEq : t_PartialEq (t_U16) (t_U16) :=
  {
    t_PartialEq_f_eq := fun (self : t_U16) (rhs : t_U16) =>
      t_PartialEq_f_eq (t_PartialEq := t_HaxInt_t_PartialEq) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs)));
    t_PartialEq_f_ne := fun (self : t_U16) (rhs : t_U16) =>
      negb (t_PartialEq_f_eq (t_PartialEq := t_HaxInt_t_PartialEq) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))));
  }.

Instance t_U16_t_PartialOrd : t_PartialOrd (t_U16) (t_U16) :=
  {
    t_PartialOrd_f_partial_cmp := fun (self : t_U16) (rhs : t_U16) =>
      t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs)));
    t_PartialOrd_f_lt := fun (self : t_U16) (rhs : t_U16) =>
      match t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))) with
      |  Option_Some (Ordering_Less) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_le := fun (self : t_U16) (rhs : t_U16) =>
      match t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))) with
      |  Option_Some (Ordering_Less
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_gt := fun (self : t_U16) (rhs : t_U16) =>
      match t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))) with
      |  Option_Some (Ordering_Greater) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_ge := fun (self : t_U16) (rhs : t_U16) =>
      match t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))) with
      |  Option_Some (Ordering_Greater
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
  }.

Instance t_U32_t_Abstraction : t_Abstraction (t_U32) :=
  {
    t_Abstraction_f_AbstractType := t_HaxInt;
    t_Abstraction_f_lift := fun (self : t_U32) =>
      t_U32_f_v self;
  }.

Instance t_U32_t_PartialEq : t_PartialEq (t_U32) (t_U32) :=
  {
    t_PartialEq_f_eq := fun (self : t_U32) (rhs : t_U32) =>
      t_PartialEq_f_eq (t_PartialEq := t_HaxInt_t_PartialEq) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs)));
    t_PartialEq_f_ne := fun (self : t_U32) (rhs : t_U32) =>
      negb (t_PartialEq_f_eq (t_PartialEq := t_HaxInt_t_PartialEq) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))));
  }.

Instance t_U32_t_PartialOrd : t_PartialOrd (t_U32) (t_U32) :=
  {
    t_PartialOrd_f_partial_cmp := fun (self : t_U32) (rhs : t_U32) =>
      t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs)));
    t_PartialOrd_f_lt := fun (self : t_U32) (rhs : t_U32) =>
      match t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))) with
      |  Option_Some (Ordering_Less) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_le := fun (self : t_U32) (rhs : t_U32) =>
      match t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))) with
      |  Option_Some (Ordering_Less
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_gt := fun (self : t_U32) (rhs : t_U32) =>
      match t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))) with
      |  Option_Some (Ordering_Greater) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_ge := fun (self : t_U32) (rhs : t_U32) =>
      match t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))) with
      |  Option_Some (Ordering_Greater
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
  }.

Instance t_U64_t_Abstraction : t_Abstraction (t_U64) :=
  {
    t_Abstraction_f_AbstractType := t_HaxInt;
    t_Abstraction_f_lift := fun (self : t_U64) =>
      t_U64_f_v self;
  }.

Instance t_U64_t_PartialEq : t_PartialEq (t_U64) (t_U64) :=
  {
    t_PartialEq_f_eq := fun (self : t_U64) (rhs : t_U64) =>
      t_PartialEq_f_eq (t_PartialEq := t_HaxInt_t_PartialEq) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs)));
    t_PartialEq_f_ne := fun (self : t_U64) (rhs : t_U64) =>
      negb (t_PartialEq_f_eq (t_PartialEq := t_HaxInt_t_PartialEq) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))));
  }.

Instance t_U64_t_PartialOrd : t_PartialOrd (t_U64) (t_U64) :=
  {
    t_PartialOrd_f_partial_cmp := fun (self : t_U64) (rhs : t_U64) =>
      t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs)));
    t_PartialOrd_f_lt := fun (self : t_U64) (rhs : t_U64) =>
      match t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))) with
      |  Option_Some (Ordering_Less) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_le := fun (self : t_U64) (rhs : t_U64) =>
      match t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))) with
      |  Option_Some (Ordering_Less
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_gt := fun (self : t_U64) (rhs : t_U64) =>
      match t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))) with
      |  Option_Some (Ordering_Greater) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_ge := fun (self : t_U64) (rhs : t_U64) =>
      match t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))) with
      |  Option_Some (Ordering_Greater
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
  }.

Instance t_U128_t_Abstraction : t_Abstraction (t_U128) :=
  {
    t_Abstraction_f_AbstractType := t_HaxInt;
    t_Abstraction_f_lift := fun (self : t_U128) =>
      t_U128_f_v self;
  }.

Instance t_U128_t_PartialEq : t_PartialEq (t_U128) (t_U128) :=
  {
    t_PartialEq_f_eq := fun (self : t_U128) (rhs : t_U128) =>
      t_PartialEq_f_eq (t_PartialEq := t_HaxInt_t_PartialEq) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs)));
    t_PartialEq_f_ne := fun (self : t_U128) (rhs : t_U128) =>
      negb (t_PartialEq_f_eq (t_PartialEq := t_HaxInt_t_PartialEq) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))));
  }.

Instance t_U128_t_PartialOrd : t_PartialOrd (t_U128) (t_U128) :=
  {
    t_PartialOrd_f_partial_cmp := fun (self : t_U128) (rhs : t_U128) =>
      t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs)));
    t_PartialOrd_f_lt := fun (self : t_U128) (rhs : t_U128) =>
      match t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))) with
      |  Option_Some (Ordering_Less) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_le := fun (self : t_U128) (rhs : t_U128) =>
      match t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))) with
      |  Option_Some (Ordering_Less
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_gt := fun (self : t_U128) (rhs : t_U128) =>
      match t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))) with
      |  Option_Some (Ordering_Greater) =>
        true
      |  _ =>
        false
      end;
    t_PartialOrd_f_ge := fun (self : t_U128) (rhs : t_U128) =>
      match t_PartialOrd_f_partial_cmp (t_PartialOrd := t_HaxInt_t_PartialOrd) (t_Abstraction_f_lift (t_Clone_f_clone (self))) (t_Abstraction_f_lift (t_Clone_f_clone (rhs))) with
      |  Option_Some (Ordering_Greater
      | Ordering_Equal) =>
        true
      |  _ =>
        false
      end;
  }.

Instance t_HaxInt_t_Concretization_t_U8 : t_Concretization (t_HaxInt) (t_U8) :=
  {
    t_Concretization_f_concretize := fun (self : t_HaxInt) =>
      Build_t_U8 (impl_10__rem (self) (v_WORDSIZE_8_));
  }.

Instance t_U8_t_From_t_U16 : t_From (t_U8) (t_U16) :=
  {
    t_From_f_from := fun (x : t_U16) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_U8_t_From_t_U32 : t_From (t_U8) (t_U32) :=
  {
    t_From_f_from := fun (x : t_U32) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_U8_t_From_t_U64 : t_From (t_U8) (t_U64) :=
  {
    t_From_f_from := fun (x : t_U64) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_U8_t_From_t_U128 : t_From (t_U8) (t_U128) :=
  {
    t_From_f_from := fun (x : t_U128) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_HaxInt_t_Concretization_t_U16 : t_Concretization (t_HaxInt) (t_U16) :=
  {
    t_Concretization_f_concretize := fun (self : t_HaxInt) =>
      Build_t_U16 (impl_10__rem (self) (v_WORDSIZE_16_));
  }.

Instance t_U16_t_From_t_U8 : t_From (t_U16) (t_U8) :=
  {
    t_From_f_from := fun (x : t_U8) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_U16_t_From_t_U32 : t_From (t_U16) (t_U32) :=
  {
    t_From_f_from := fun (x : t_U32) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_U16_t_From_t_U64 : t_From (t_U16) (t_U64) :=
  {
    t_From_f_from := fun (x : t_U64) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_U16_t_From_t_U128 : t_From (t_U16) (t_U128) :=
  {
    t_From_f_from := fun (x : t_U128) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_HaxInt_t_Concretization_t_U32 : t_Concretization (t_HaxInt) (t_U32) :=
  {
    t_Concretization_f_concretize := fun (self : t_HaxInt) =>
      Build_t_U32 (impl_10__rem (self) (v_WORDSIZE_32_));
  }.

Instance t_U32_t_From_t_U8 : t_From (t_U32) (t_U8) :=
  {
    t_From_f_from := fun (x : t_U8) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_U32_t_From_t_U16 : t_From (t_U32) (t_U16) :=
  {
    t_From_f_from := fun (x : t_U16) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_U32_t_From_t_U64 : t_From (t_U32) (t_U64) :=
  {
    t_From_f_from := fun (x : t_U64) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_U32_t_From_t_U128 : t_From (t_U32) (t_U128) :=
  {
    t_From_f_from := fun (x : t_U128) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_HaxInt_t_Concretization_t_U64 : t_Concretization (t_HaxInt) (t_U64) :=
  {
    t_Concretization_f_concretize := fun (self : t_HaxInt) =>
      Build_t_U64 (impl_10__rem (self) (v_WORDSIZE_64_));
  }.

Instance t_U64_t_From_t_U8 : t_From (t_U64) (t_U8) :=
  {
    t_From_f_from := fun (x : t_U8) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_U64_t_From_t_U16 : t_From (t_U64) (t_U16) :=
  {
    t_From_f_from := fun (x : t_U16) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_U64_t_From_t_U32 : t_From (t_U64) (t_U32) :=
  {
    t_From_f_from := fun (x : t_U32) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_U64_t_From_t_U128 : t_From (t_U64) (t_U128) :=
  {
    t_From_f_from := fun (x : t_U128) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_HaxInt_t_Concretization_t_U128 : t_Concretization (t_HaxInt) (t_U128) :=
  {
    t_Concretization_f_concretize := fun (self : t_HaxInt) =>
      Build_t_U128 (impl_10__rem (self) (v_WORDSIZE_128_));
  }.

Instance t_U128_t_From_t_U8 : t_From (t_U128) (t_U8) :=
  {
    t_From_f_from := fun (x : t_U8) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_U128_t_From_t_U16 : t_From (t_U128) (t_U16) :=
  {
    t_From_f_from := fun (x : t_U16) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_U128_t_From_t_U32 : t_From (t_U128) (t_U32) :=
  {
    t_From_f_from := fun (x : t_U32) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_U128_t_From_t_U64 : t_From (t_U128) (t_U64) :=
  {
    t_From_f_from := fun (x : t_U64) =>
      t_Concretization_f_concretize (t_Abstraction_f_lift (x) : t_HaxInt);
  }.

Instance t_U8_t_Neg : t_Neg (t_U8) :=
  {
    t_Neg_f_Output := t_U8;
    t_Neg_f_neg := fun (self : t_U8) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U8) (impl_7__sub (v_WORDSIZE_8_) (impl_10__rem (t_Abstraction_f_lift (self)) (v_WORDSIZE_8_)));
  }.

Instance t_U8_t_Mul : t_Mul (t_U8) (t_U8) :=
  {
    t_Mul_f_Output := t_U8;
    t_Mul_f_mul := fun (self : t_U8) (rhs : t_U8) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U8) (impl_11__mul (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U8_t_Rem : t_Rem (t_U8) (t_U8) :=
  {
    t_Rem_f_Output := t_U8;
    t_Rem_f_rem := fun (self : t_U8) (rhs : t_U8) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U8) (impl_10__rem (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U8_t_Add : t_Add (t_U8) (t_U8) :=
  {
    t_Add_f_Output := t_U8;
    t_Add_f_add := fun (self : t_U8) (rhs : t_U8) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U8) (impl_6__add (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U8_t_Div : t_Div (t_U8) (t_U8) :=
  {
    t_Div_f_Output := t_U8;
    t_Div_f_div := fun (self : t_U8) (rhs : t_U8) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U8) (impl_10__div (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U8_t_Shl_t_U8 : t_Shl (t_U8) (t_U8) :=
  {
    t_Shl_f_Output := t_U8;
    t_Shl_f_shl := fun (self : t_U8) (rhs : t_U8) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U8) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U8_t_Shl_t_U16 : t_Shl (t_U8) (t_U16) :=
  {
    t_Shl_f_Output := t_U8;
    t_Shl_f_shl := fun (self : t_U8) (rhs : t_U16) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U8) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U8_t_Shl_t_U32 : t_Shl (t_U8) (t_U32) :=
  {
    t_Shl_f_Output := t_U8;
    t_Shl_f_shl := fun (self : t_U8) (rhs : t_U32) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U8) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U8_t_Shl_t_U64 : t_Shl (t_U8) (t_U64) :=
  {
    t_Shl_f_Output := t_U8;
    t_Shl_f_shl := fun (self : t_U8) (rhs : t_U64) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U8) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U8_t_Shl_t_U128 : t_Shl (t_U8) (t_U128) :=
  {
    t_Shl_f_Output := t_U8;
    t_Shl_f_shl := fun (self : t_U8) (rhs : t_U128) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U8) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U8_t_Shr_t_U8 : t_Shr (t_U8) (t_U8) :=
  {
    t_Shr_f_Output := t_U8;
    t_Shr_f_shr := fun (self : t_U8) (rhs : t_U8) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U8) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U8_t_Shr_t_U16 : t_Shr (t_U8) (t_U16) :=
  {
    t_Shr_f_Output := t_U8;
    t_Shr_f_shr := fun (self : t_U8) (rhs : t_U16) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U8) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U8_t_Shr_t_U32 : t_Shr (t_U8) (t_U32) :=
  {
    t_Shr_f_Output := t_U8;
    t_Shr_f_shr := fun (self : t_U8) (rhs : t_U32) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U8) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U8_t_Shr_t_U64 : t_Shr (t_U8) (t_U64) :=
  {
    t_Shr_f_Output := t_U8;
    t_Shr_f_shr := fun (self : t_U8) (rhs : t_U64) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U8) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U8_t_Shr_t_U128 : t_Shr (t_U8) (t_U128) :=
  {
    t_Shr_f_Output := t_U8;
    t_Shr_f_shr := fun (self : t_U8) (rhs : t_U128) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U8) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U8_t_BitXor : t_BitXor (t_U8) (t_U8) :=
  {
    t_BitXor_f_Output := t_U8;
    t_BitXor_f_bitxor := fun (self : t_U8) (rhs : t_U8) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U8) (impl_14__bitxor (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U8_t_BitAnd : t_BitAnd (t_U8) (t_U8) :=
  {
    t_BitAnd_f_Output := t_U8;
    t_BitAnd_f_bitand := fun (self : t_U8) (rhs : t_U8) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U8) (impl_15__bitand (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U8_t_BitOr : t_BitOr (t_U8) (t_U8) :=
  {
    t_BitOr_f_Output := t_U8;
    t_BitOr_f_bitor := fun (self : t_U8) (rhs : t_U8) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U8) (impl_16__bitor (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U16_t_Neg : t_Neg (t_U16) :=
  {
    t_Neg_f_Output := t_U16;
    t_Neg_f_neg := fun (self : t_U16) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U16) (impl_7__sub (v_WORDSIZE_16_) (impl_10__rem (t_Abstraction_f_lift (self)) (v_WORDSIZE_16_)));
  }.

Instance t_U16_t_Mul : t_Mul (t_U16) (t_U16) :=
  {
    t_Mul_f_Output := t_U16;
    t_Mul_f_mul := fun (self : t_U16) (rhs : t_U16) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U16) (impl_11__mul (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U16_t_Rem : t_Rem (t_U16) (t_U16) :=
  {
    t_Rem_f_Output := t_U16;
    t_Rem_f_rem := fun (self : t_U16) (rhs : t_U16) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U16) (impl_10__rem (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U16_t_Add : t_Add (t_U16) (t_U16) :=
  {
    t_Add_f_Output := t_U16;
    t_Add_f_add := fun (self : t_U16) (rhs : t_U16) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U16) (impl_6__add (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U16_t_Div : t_Div (t_U16) (t_U16) :=
  {
    t_Div_f_Output := t_U16;
    t_Div_f_div := fun (self : t_U16) (rhs : t_U16) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U16) (impl_10__div (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U16_t_Shl_t_U8 : t_Shl (t_U16) (t_U8) :=
  {
    t_Shl_f_Output := t_U16;
    t_Shl_f_shl := fun (self : t_U16) (rhs : t_U8) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U16) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U16_t_Shl_t_U16 : t_Shl (t_U16) (t_U16) :=
  {
    t_Shl_f_Output := t_U16;
    t_Shl_f_shl := fun (self : t_U16) (rhs : t_U16) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U16) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U16_t_Shl_t_U32 : t_Shl (t_U16) (t_U32) :=
  {
    t_Shl_f_Output := t_U16;
    t_Shl_f_shl := fun (self : t_U16) (rhs : t_U32) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U16) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U16_t_Shl_t_U64 : t_Shl (t_U16) (t_U64) :=
  {
    t_Shl_f_Output := t_U16;
    t_Shl_f_shl := fun (self : t_U16) (rhs : t_U64) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U16) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U16_t_Shl_t_U128 : t_Shl (t_U16) (t_U128) :=
  {
    t_Shl_f_Output := t_U16;
    t_Shl_f_shl := fun (self : t_U16) (rhs : t_U128) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U16) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U16_t_Shr_t_U8 : t_Shr (t_U16) (t_U8) :=
  {
    t_Shr_f_Output := t_U16;
    t_Shr_f_shr := fun (self : t_U16) (rhs : t_U8) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U16) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U16_t_Shr_t_U16 : t_Shr (t_U16) (t_U16) :=
  {
    t_Shr_f_Output := t_U16;
    t_Shr_f_shr := fun (self : t_U16) (rhs : t_U16) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U16) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U16_t_Shr_t_U32 : t_Shr (t_U16) (t_U32) :=
  {
    t_Shr_f_Output := t_U16;
    t_Shr_f_shr := fun (self : t_U16) (rhs : t_U32) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U16) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U16_t_Shr_t_U64 : t_Shr (t_U16) (t_U64) :=
  {
    t_Shr_f_Output := t_U16;
    t_Shr_f_shr := fun (self : t_U16) (rhs : t_U64) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U16) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U16_t_Shr_t_U128 : t_Shr (t_U16) (t_U128) :=
  {
    t_Shr_f_Output := t_U16;
    t_Shr_f_shr := fun (self : t_U16) (rhs : t_U128) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U16) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U16_t_BitXor : t_BitXor (t_U16) (t_U16) :=
  {
    t_BitXor_f_Output := t_U16;
    t_BitXor_f_bitxor := fun (self : t_U16) (rhs : t_U16) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U16) (impl_14__bitxor (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U16_t_BitAnd : t_BitAnd (t_U16) (t_U16) :=
  {
    t_BitAnd_f_Output := t_U16;
    t_BitAnd_f_bitand := fun (self : t_U16) (rhs : t_U16) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U16) (impl_15__bitand (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U16_t_BitOr : t_BitOr (t_U16) (t_U16) :=
  {
    t_BitOr_f_Output := t_U16;
    t_BitOr_f_bitor := fun (self : t_U16) (rhs : t_U16) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U16) (impl_16__bitor (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U32_t_Neg : t_Neg (t_U32) :=
  {
    t_Neg_f_Output := t_U32;
    t_Neg_f_neg := fun (self : t_U32) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U32) (impl_7__sub (v_WORDSIZE_32_) (impl_10__rem (t_Abstraction_f_lift (self)) (v_WORDSIZE_32_)));
  }.

Instance t_U32_t_Mul : t_Mul (t_U32) (t_U32) :=
  {
    t_Mul_f_Output := t_U32;
    t_Mul_f_mul := fun (self : t_U32) (rhs : t_U32) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U32) (impl_11__mul (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U32_t_Rem : t_Rem (t_U32) (t_U32) :=
  {
    t_Rem_f_Output := t_U32;
    t_Rem_f_rem := fun (self : t_U32) (rhs : t_U32) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U32) (impl_10__rem (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U32_t_Add : t_Add (t_U32) (t_U32) :=
  {
    t_Add_f_Output := t_U32;
    t_Add_f_add := fun (self : t_U32) (rhs : t_U32) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U32) (impl_6__add (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U32_t_Div : t_Div (t_U32) (t_U32) :=
  {
    t_Div_f_Output := t_U32;
    t_Div_f_div := fun (self : t_U32) (rhs : t_U32) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U32) (impl_10__div (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U32_t_Shl : t_Shl (t_U32) (t_U8) :=
  {
    t_Shl_f_Output := t_U32;
    t_Shl_f_shl := fun (self : t_U32) (rhs : t_U8) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U32) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U32_t_Shl_t_U16 : t_Shl (t_U32) (t_U16) :=
  {
    t_Shl_f_Output := t_U32;
    t_Shl_f_shl := fun (self : t_U32) (rhs : t_U16) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U32) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U32_t_Shl_t_U32 : t_Shl (t_U32) (t_U32) :=
  {
    t_Shl_f_Output := t_U32;
    t_Shl_f_shl := fun (self : t_U32) (rhs : t_U32) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U32) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U32_t_Shl_t_U64 : t_Shl (t_U32) (t_U64) :=
  {
    t_Shl_f_Output := t_U32;
    t_Shl_f_shl := fun (self : t_U32) (rhs : t_U64) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U32) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U32_t_Shl_t_U128 : t_Shl (t_U32) (t_U128) :=
  {
    t_Shl_f_Output := t_U32;
    t_Shl_f_shl := fun (self : t_U32) (rhs : t_U128) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U32) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U32_t_Shr_t_U8 : t_Shr (t_U32) (t_U8) :=
  {
    t_Shr_f_Output := t_U32;
    t_Shr_f_shr := fun (self : t_U32) (rhs : t_U8) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U32) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U32_t_Shr_t_U16 : t_Shr (t_U32) (t_U16) :=
  {
    t_Shr_f_Output := t_U32;
    t_Shr_f_shr := fun (self : t_U32) (rhs : t_U16) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U32) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U32_t_Shr_t_U32 : t_Shr (t_U32) (t_U32) :=
  {
    t_Shr_f_Output := t_U32;
    t_Shr_f_shr := fun (self : t_U32) (rhs : t_U32) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U32) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U32_t_Shr_t_U64 : t_Shr (t_U32) (t_U64) :=
  {
    t_Shr_f_Output := t_U32;
    t_Shr_f_shr := fun (self : t_U32) (rhs : t_U64) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U32) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U32_t_Shr_t_U128 : t_Shr (t_U32) (t_U128) :=
  {
    t_Shr_f_Output := t_U32;
    t_Shr_f_shr := fun (self : t_U32) (rhs : t_U128) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U32) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U32_t_BitXor : t_BitXor (t_U32) (t_U32) :=
  {
    t_BitXor_f_Output := t_U32;
    t_BitXor_f_bitxor := fun (self : t_U32) (rhs : t_U32) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U32) (impl_14__bitxor (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U32_t_BitAnd : t_BitAnd (t_U32) (t_U32) :=
  {
    t_BitAnd_f_Output := t_U32;
    t_BitAnd_f_bitand := fun (self : t_U32) (rhs : t_U32) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U32) (impl_15__bitand (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U32_t_BitOr : t_BitOr (t_U32) (t_U32) :=
  {
    t_BitOr_f_Output := t_U32;
    t_BitOr_f_bitor := fun (self : t_U32) (rhs : t_U32) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U32) (impl_16__bitor (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U64_t_Neg : t_Neg (t_U64) :=
  {
    t_Neg_f_Output := t_U64;
    t_Neg_f_neg := fun (self : t_U64) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U64) (impl_7__sub (v_WORDSIZE_64_) (impl_10__rem (t_Abstraction_f_lift (self)) (v_WORDSIZE_64_)));
  }.

Instance t_U64_t_Mul : t_Mul (t_U64) (t_U64) :=
  {
    t_Mul_f_Output := t_U64;
    t_Mul_f_mul := fun (self : t_U64) (rhs : t_U64) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U64) (impl_11__mul (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U64_t_Rem : t_Rem (t_U64) (t_U64) :=
  {
    t_Rem_f_Output := t_U64;
    t_Rem_f_rem := fun (self : t_U64) (rhs : t_U64) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U64) (impl_10__rem (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U64_t_Add : t_Add (t_U64) (t_U64) :=
  {
    t_Add_f_Output := t_U64;
    t_Add_f_add := fun (self : t_U64) (rhs : t_U64) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U64) (impl_6__add (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U64_t_Div : t_Div (t_U64) (t_U64) :=
  {
    t_Div_f_Output := t_U64;
    t_Div_f_div := fun (self : t_U64) (rhs : t_U64) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U64) (impl_10__div (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U64_t_Shl_t_U8 : t_Shl (t_U64) (t_U8) :=
  {
    t_Shl_f_Output := t_U64;
    t_Shl_f_shl := fun (self : t_U64) (rhs : t_U8) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U64) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U64_t_Shl_t_U16 : t_Shl (t_U64) (t_U16) :=
  {
    t_Shl_f_Output := t_U64;
    t_Shl_f_shl := fun (self : t_U64) (rhs : t_U16) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U64) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U64_t_Shl_t_U32 : t_Shl (t_U64) (t_U32) :=
  {
    t_Shl_f_Output := t_U64;
    t_Shl_f_shl := fun (self : t_U64) (rhs : t_U32) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U64) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U64_t_Shl_t_U64 : t_Shl (t_U64) (t_U64) :=
  {
    t_Shl_f_Output := t_U64;
    t_Shl_f_shl := fun (self : t_U64) (rhs : t_U64) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U64) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U64_t_Shl_t_U128 : t_Shl (t_U64) (t_U128) :=
  {
    t_Shl_f_Output := t_U64;
    t_Shl_f_shl := fun (self : t_U64) (rhs : t_U128) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U64) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U64_t_Shr_t_U8 : t_Shr (t_U64) (t_U8) :=
  {
    t_Shr_f_Output := t_U64;
    t_Shr_f_shr := fun (self : t_U64) (rhs : t_U8) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U64) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U64_t_Shr_t_U16 : t_Shr (t_U64) (t_U16) :=
  {
    t_Shr_f_Output := t_U64;
    t_Shr_f_shr := fun (self : t_U64) (rhs : t_U16) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U64) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U64_t_Shr_t_U32 : t_Shr (t_U64) (t_U32) :=
  {
    t_Shr_f_Output := t_U64;
    t_Shr_f_shr := fun (self : t_U64) (rhs : t_U32) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U64) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U64_t_Shr_t_U64 : t_Shr (t_U64) (t_U64) :=
  {
    t_Shr_f_Output := t_U64;
    t_Shr_f_shr := fun (self : t_U64) (rhs : t_U64) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U64) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U64_t_Shr_t_U128 : t_Shr (t_U64) (t_U128) :=
  {
    t_Shr_f_Output := t_U64;
    t_Shr_f_shr := fun (self : t_U64) (rhs : t_U128) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U64) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U64_t_BitXor : t_BitXor (t_U64) (t_U64) :=
  {
    t_BitXor_f_Output := t_U64;
    t_BitXor_f_bitxor := fun (self : t_U64) (rhs : t_U64) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U64) (impl_14__bitxor (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U64_t_BitAnd : t_BitAnd (t_U64) (t_U64) :=
  {
    t_BitAnd_f_Output := t_U64;
    t_BitAnd_f_bitand := fun (self : t_U64) (rhs : t_U64) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U64) (impl_15__bitand (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U64_t_BitOr : t_BitOr (t_U64) (t_U64) :=
  {
    t_BitOr_f_Output := t_U64;
    t_BitOr_f_bitor := fun (self : t_U64) (rhs : t_U64) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U64) (impl_16__bitor (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U128_t_Neg : t_Neg (t_U128) :=
  {
    t_Neg_f_Output := t_U128;
    t_Neg_f_neg := fun (self : t_U128) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U128) (impl_7__sub (v_WORDSIZE_128_) (impl_10__rem (t_Abstraction_f_lift (self)) (v_WORDSIZE_128_)));
  }.

Instance t_U128_t_Mul : t_Mul (t_U128) (t_U128) :=
  {
    t_Mul_f_Output := t_U128;
    t_Mul_f_mul := fun (self : t_U128) (rhs : t_U128) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U128) (impl_11__mul (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U128_t_Rem : t_Rem (t_U128) (t_U128) :=
  {
    t_Rem_f_Output := t_U128;
    t_Rem_f_rem := fun (self : t_U128) (rhs : t_U128) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U128) (impl_10__rem (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U128_t_Add : t_Add (t_U128) (t_U128) :=
  {
    t_Add_f_Output := t_U128;
    t_Add_f_add := fun (self : t_U128) (rhs : t_U128) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U128) (impl_6__add (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U128_t_Div : t_Div (t_U128) (t_U128) :=
  {
    t_Div_f_Output := t_U128;
    t_Div_f_div := fun (self : t_U128) (rhs : t_U128) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U128) (impl_10__div (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U128_t_Shl_t_U8 : t_Shl (t_U128) (t_U8) :=
  {
    t_Shl_f_Output := t_U128;
    t_Shl_f_shl := fun (self : t_U128) (rhs : t_U8) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U128) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U128_t_Shl_t_U16 : t_Shl (t_U128) (t_U16) :=
  {
    t_Shl_f_Output := t_U128;
    t_Shl_f_shl := fun (self : t_U128) (rhs : t_U16) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U128) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U128_t_Shl_t_U32 : t_Shl (t_U128) (t_U32) :=
  {
    t_Shl_f_Output := t_U128;
    t_Shl_f_shl := fun (self : t_U128) (rhs : t_U32) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U128) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U128_t_Shl_t_U64 : t_Shl (t_U128) (t_U64) :=
  {
    t_Shl_f_Output := t_U128;
    t_Shl_f_shl := fun (self : t_U128) (rhs : t_U64) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U128) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U128_t_Shl_t_U128 : t_Shl (t_U128) (t_U128) :=
  {
    t_Shl_f_Output := t_U128;
    t_Shl_f_shl := fun (self : t_U128) (rhs : t_U128) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U128) (impl_12__shl (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U128_t_Shr_t_U8 : t_Shr (t_U128) (t_U8) :=
  {
    t_Shr_f_Output := t_U128;
    t_Shr_f_shr := fun (self : t_U128) (rhs : t_U8) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U128) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U128_t_Shr_t_U16 : t_Shr (t_U128) (t_U16) :=
  {
    t_Shr_f_Output := t_U128;
    t_Shr_f_shr := fun (self : t_U128) (rhs : t_U16) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U128) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U128_t_Shr_t_U32 : t_Shr (t_U128) (t_U32) :=
  {
    t_Shr_f_Output := t_U128;
    t_Shr_f_shr := fun (self : t_U128) (rhs : t_U32) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U128) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U128_t_Shr_t_U64 : t_Shr (t_U128) (t_U64) :=
  {
    t_Shr_f_Output := t_U128;
    t_Shr_f_shr := fun (self : t_U128) (rhs : t_U64) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U128) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U128_t_Shr_t_U128 : t_Shr (t_U128) (t_U128) :=
  {
    t_Shr_f_Output := t_U128;
    t_Shr_f_shr := fun (self : t_U128) (rhs : t_U128) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U128) (impl_13__shr (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U128_t_BitXor : t_BitXor (t_U128) (t_U128) :=
  {
    t_BitXor_f_Output := t_U128;
    t_BitXor_f_bitxor := fun (self : t_U128) (rhs : t_U128) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U128) (impl_14__bitxor (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U128_t_BitAnd : t_BitAnd (t_U128) (t_U128) :=
  {
    t_BitAnd_f_Output := t_U128;
    t_BitAnd_f_bitand := fun (self : t_U128) (rhs : t_U128) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U128) (impl_15__bitand (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U128_t_BitOr : t_BitOr (t_U128) (t_U128) :=
  {
    t_BitOr_f_Output := t_U128;
    t_BitOr_f_bitor := fun (self : t_U128) (rhs : t_U128) =>
      t_Concretization_f_concretize (t_Concretization := t_HaxInt_t_Concretization_t_U128) (impl_16__bitor (t_Abstraction_f_lift (self)) (t_Abstraction_f_lift (rhs)));
  }.

Instance t_U8_t_Sub : t_Sub (t_U8) (t_U8) :=
  {
    t_Sub_f_Output := t_U8;
    t_Sub_f_sub := fun (self : t_U8) (rhs : t_U8) =>
      t_Add_f_add (t_Add := t_U8_t_Add) (self) (t_Neg_f_neg (rhs));
  }.

Instance t_U8_t_Not : t_Not (t_U8) :=
  {
    t_Not_f_Output := t_U8;
    t_Not_f_not := fun (self : t_U8) =>
      t_BitXor_f_bitxor (self) (t_Constants_f_MAX);
  }.

Instance t_U16_t_Sub : t_Sub (t_U16) (t_U16) :=
  {
    t_Sub_f_Output := t_U16;
    t_Sub_f_sub := fun (self : t_U16) (rhs : t_U16) =>
      t_Add_f_add (t_Add := t_U16_t_Add) (self) (t_Neg_f_neg (rhs));
  }.

Instance t_U16_t_Not : t_Not (t_U16) :=
  {
    t_Not_f_Output := t_U16;
    t_Not_f_not := fun (self : t_U16) =>
      t_BitXor_f_bitxor (self) (t_Constants_f_MAX);
  }.

Instance t_U32_t_Sub : t_Sub (t_U32) (t_U32) :=
  {
    t_Sub_f_Output := t_U32;
    t_Sub_f_sub := fun (self : t_U32) (rhs : t_U32) =>
      t_Add_f_add (t_Add := t_U32_t_Add) (self) (t_Neg_f_neg (rhs));
  }.

Instance t_U32_t_Not : t_Not (t_U32) :=
  {
    t_Not_f_Output := t_U32;
    t_Not_f_not := fun (self : t_U32) =>
      t_BitXor_f_bitxor (self) (t_Constants_f_MAX);
  }.

Instance t_U64_t_Sub : t_Sub (t_U64) (t_U64) :=
  {
    t_Sub_f_Output := t_U64;
    t_Sub_f_sub := fun (self : t_U64) (rhs : t_U64) =>
      t_Add_f_add (t_Add := t_U64_t_Add) (self) (t_Neg_f_neg (rhs));
  }.

Instance t_U64_t_Not : t_Not (t_U64) :=
  {
    t_Not_f_Output := t_U64;
    t_Not_f_not := fun (self : t_U64) =>
      t_BitXor_f_bitxor (self) (t_Constants_f_MAX);
  }.

Instance t_U128_t_Sub : t_Sub (t_U128) (t_U128) :=
  {
    t_Sub_f_Output := t_U128;
    t_Sub_f_sub := fun (self : t_U128) (rhs : t_U128) =>
      t_Add_f_add (t_Add := t_U128_t_Add) (self) (t_Neg_f_neg (rhs));
  }.

Instance t_U128_t_Not : t_Not (t_U128) :=
  {
    t_Not_f_Output := t_U128;
    t_Not_f_not := fun (self : t_U128) =>
      t_BitXor_f_bitxor (self) (t_Constants_f_MAX);
  }.
