use crate::prelude::*;
use crate::sinto_todo;
sinto_todo!(rustc_middle::mir::interpret, Scalar);
sinto_todo!(rustc_middle::ty, ScalarInt);
sinto_todo!(rustc_middle::ty, ExistentialPredicate<'a>);
sinto_todo!(rustc_middle::ty, Region<'s>);
sinto_todo!(rustc_middle::ty, PolyFnSig<'s>);
sinto_todo!(rustc_middle::ty, AdtFlags);
sinto_todo!(rustc_middle::mir::interpret, ConstAllocation<'a>);
sinto_todo!(rustc_ast::tokenstream, DelimSpan);
sinto_todo!(rustc_hir::def, DefKind);
sinto_todo!(rustc_hir, GenericArgs<'a> as HirGenericArgs);
sinto_todo!(rustc_hir, InlineAsm<'a>);
sinto_todo!(rustc_target::spec::abi, Abi);
sinto_todo!(rustc_hir, WhereRegionPredicate<'tcx>);
sinto_todo!(rustc_hir, WhereEqPredicate<'tcx>);
sinto_todo!(rustc_hir, OwnerId);
