(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

Require Import Core_Primitive.
Export Core_Primitive.

(* Array coercions *)
Coercion Build_t_Array : t_Slice >-> t_Array.
Coercion Build_t_Slice : list >-> t_Slice.

Definition unsize {A} (x : A) := x.
Definition repeat {v_T} (a : v_T) b : t_Array v_T b := List.repeat a (N.to_nat (U64_f_v (usize_0 b))).

Definition t_String := string.
Definition ToString_f_to_string (x : string) : string := x.
